#!/bin/bash

scriptroot="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "cross-tool/.build-done" ]]; then
	"$scriptroot/build-crossgcc.sh" \
		-a x86_64-elf -o cross-build -p cross-tool -j 16 || exit
	export PATH=$PATH:$PWD/cross-tool/bin
	CFLAGS="-nostartfiles -nostdlib" CXXFLAGS=$CFLAGS \
		"$scriptroot/configure" --host x86_64-elf || exit
	make musl || exit
	cp -R musl-install/* cross-tool/x86_64-elf || exit
	touch "cross-tool/.build-done" || exit
	make || exit
fi
