#!/bin/bash

scriptroot="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "cross-tool/.build-done" ]]; then
	nice "$scriptroot/build-crossgcc.bash" \
		-a x86_64-elf -o cross-build -p cross-tool -j $(nproc) || exit
	export PATH=$PATH:$PWD/cross-tool/bin
	CFLAGS="-nostartfiles -nostdlib" CXXFLAGS="$CFLAGS" \
		"$scriptroot/configure" --host x86_64-dgos || exit
	make libc.a || exit
#	touch "cross-tool/.build-done" || exit
#    "$scriptroot/configure" --host x86_64-dgos
#	make || exit
fi
