#!/bin/bash

#set -x

scriptroot="$(cd "$(dirname "$0")" && pwd)"

function join_by {
	local IFS="$1"
	shift
	echo "$*"
}

HOST=x86_64-elf
AR="$HOST-gcc-ar"
RANLIB="$HOST-gcc-ranlib"
NM="$HOST-gcc-nm"

export AR
export RANLIB
export NM

if [[ ! -f sysroot/libc/libc.a ]]; then
	echo Bootstrapping sysroot
	compileflags=( "-nostdlib" "-nostartfiles" )
	configureflags=()

	CFLAGS="$(join_by ' ' ${compileflags[@]})" \
		CXXFLAGS="$CFLAGS" \
		LDFLAGS="$CFLAGS" \
		"$scriptroot/configure" --host "$HOST" \
		$(join_by ' ' ${configureflags[@]}) "$@" && \
		nice make -j $(nproc) \
			sysroot/lib/crt0.o \
			sysroot/lib/libc.a \
			sysroot/lib/libm.a \
			sysroot/lib/libstdc++.a
fi

compileflags=( "--sysroot sysroot" )
configureflags=()
done=0

echo flags: "${compileflags[@]}"

CFLAGS="$(join_by ' ' ${compileflags[@]})" \
	CXXFLAGS="$CFLAGS" \
	LDFLAGS="$CFLAGS" \
	"$scriptroot/configure" --host "$HOST" \
	$(join_by ' ' ${configureflags[@]}) "$@"
