#!/bin/bash

#set -x

scriptroot="$(cd "$(dirname "$0")" && pwd)"

function join_by {
	local IFS="$1"
	shift
	echo "$*"
}

HOST=x86_64-elf
AR="$HOST-gcc-ar"
RANLIB="$HOST-gcc-ranlib"
NM="$HOST-gcc-nm"

export AR
export RANLIB
export NM

if [[ ! -f sysroot/libc/libc.a ]]; then
	echo Bootstrapping sysroot
	compileflags=( "-nostdlib" "-nostartfiles" )
	configureflags=()
set +x
		"$scriptroot/configure" --host "$HOST" \
		CFLAGS="$(join_by ' ' ${compileflags[@]})" \
			CXXFLAGS="$CFLAGS" \
			LDFLAGS="$CFLAGS" \
		"$(join_by ' ' ${configureflags[@]})" "$@" && \
		nice make --trace -j $(nproc) \
			sysroot/lib/crt0.o \
			sysroot/lib/crt0pc32.o \
			sysroot/lib/crt0pc64.o \
			sysroot/lib/crt0pc80.o \
			sysroot/lib/libc.a \
			startupcode

fi

compileflags=( "--sysroot sysroot" )
configureflags=()

echo flags: "${compileflags[@]}"

CFLAGS="$(join_by ' ' ${compileflags[@]})" \
	CXXFLAGS="$CFLAGS" \
	LDFLAGS="$CFLAGS" \
	"$scriptroot/configure" --host "$HOST" \
	$(join_by ' ' ${configureflags[@]}) "$@"
