#!/bin/bash

#set -x

scriptroot="$(cd "$(dirname "$0")" && pwd)"

HOST=x86_64-elf
AR="$HOST-ar"
RANLIB="$HOST-ranlib"
NM="$HOST-nm"

export AR
export RANLIB
export NM

compileflags=( "-nostdlib" "-ffreestanding" )
configureflags=()
done=0

function join_by {
	local IFS="$1"
	shift
	echo "$*"
}

while [[ $done == 0 ]]
do
	case "$1" in
	--with-lto )
		shift
		compileflags+=("-flto=16")
		configureflags+=("--enable-optimize")
		AR="$HOST-gcc-ar"
		RANLIB="$HOST-gcc-ranlib"
		NM="$HOST-gcc-nm"
		;;
	* ) done=1 ;;
	esac
done

echo flags: "${compileflags[@]}"

CFLAGS="$(join_by ' ' ${compileflags[@]})" CXXFLAGS="$CFLAGS" LDFLAGS="$CFLAGS" \
	"$scriptroot/configure" --host "$HOST" \
	$(join_by ' ' ${configureflags[@]}) "$@"
