#!/bin/bash
echo Generating qemu-emu.mk
rm -f qemu-emu.mk

# Generate {debug|run}-{up|smp}-{bios|efi}-{pxe|hd}-{iso|fat}-\
# {ahci|ide|nvme|usb}-{kvm|tcg}

# Disallow nvme with iso

for rt in debug run
do
	for np in up smp
	do	
		for bt in bios efi
		do
			for bm in pxe hd
			do
				for fs in iso fat
				do
					for sc in ahci ide nvme usb
					do
						for em in kvm tcg
						do
							if [[ $fs = "iso" ]] && [[ $sc = "nvme" ]]; then
								continue
							fi

							printf %s \
								"$rt-$np-$bt-$bm-$fs-$sc-$em:" \
								" \$(call QEMU_IMAGE,$fs)" \
								" \$(QEMU_EXTRA_DEPS)" \
								$'\n' $'\t' \
								'echo -e -n ' $'\'' '\ec' $'\'' \
								' >> dump/qemu-debug-out' \
								$'\n' $'\t' \
								"\$(QEMU_SUDO) \$(QEMU)" \
								' \' $'\n' $'\t\t' \
								"\$(QEMU_EARLY)" \
								' \' $'\n' $'\t\t' \
								"\$(QEMU_COMMON)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_EMU,$em)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_DRV,$fs,$sc)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_NP,$np)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_HDCTL,""$sc"",""$fs"")" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_BOOT,$bt)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_RT,$rt)" \
								' \' $'\n' $'\t\t' \
								"\$(call QEMU_BOOTMEDIA,$bm,$bt)" \
								' \' $'\n' $'\t\t' \
								"\$(QEMU_EXTRA)" \
								$'\n' $'\n' \
								'.PHONY: ' "$rt-$np-$bt-$bm-$fs-$sc-$em" \
								$'\n' $'\n' \
								>> qemu-emu.mk
						done
					done
				done
			done
		done
	done
done

# '-drive' \
# " file=$IMG$DIF,format=raw,media=$QM" \
# ",werror=report,rerror=report,id=bootdrv"
