#!/bin/bash
echo Generating qemu-emu.mk
rm -f qemu-emu.mk
for rt in debug run
do
	for np in up smp
	do
		for bt in bios efi
		do
			for fs in iso fat
			do
				for sc in ahci ide nvme usb
				do
					for em in kvm tcg
					do
						IMG="\$(QEMU_IMAGE_$fs)"
						QUP="\$(QEMU_NP_$np)"
						CTL="\$(QEMU_HDCTL_DEV_{$sc}_{$fs})"
						DIF="\$(QEMU_DIF_$sc)"
						QM="\$(QEMU_MEDIA_$fs)"
						BOOT="\$(QEMU_BOOT_$bt)"
						QEM="\$(QEMU_EMU_$em)"
						QRT="\$(QEMU_RT_$rt)"
						printf %s \
							"$rt-$np-$bt-$fs-$sc-$em: " \
							$IMG \
							' $(QEMU_EXTRA_DEPS)' \
							$'\n' $'\t' \
							'echo -e -n ' $'\'' '\ec' $'\'' \
							' >> dump/qemu-debug-out' \
							$'\n' $'\t' \
							'$(QEMU_SUDO) $(QEMU) $(QEMU_COMMON)' \
							' \' $'\n' $'\t\t' \
							$QUP \
							' \' $'\n' $'\t\t' \
							$CTL \
							' \' $'\n' $'\t\t' \
							$QEM \
							' \' $'\n' $'\t\t' \
							$BOOT \
							' \' $'\n' $'\t\t' \
							'-drive' \
							" file=$IMG$DIF,format=raw,media=$QM" \
							",werror=report,rerror=report" \
							' \' $'\n' $'\t\t' \
							$QRT \
							' \' $'\n' $'\t\t' \
							"\$(QEMU_EXTRA)" \
							$'\n' $'\n' \
							'.PHONY: ' "$rt-$np-$fs-$sc-$em" \
							$'\n' $'\n' \
							>> qemu-emu.mk
					done
				done
			done
		done
	done
done
