#!/usr/bin/expect

set timeout -1
set host [lindex $argv 0]
set port [lindex $argv 1]
spawn telnet $host $port
foreach cmd [lrange $argv 2 $argc] {
	expect "(qemu) "
	send "$cmd\n"
}
expect "(qemu) "
send "\x1d"
send "close\n"
send_user "\n"

