// THIS FILE IS AUTOMATICALLY GENERATED
// from kernel/device/usb_audio/usb_audio.bits

//
// USB_AUDIO_CH_CFG: Bitmask of positions present in cluster


// Front Left
#define USB_AUDIO_CH_CFG_FL_BIT         0

// Front Right
#define USB_AUDIO_CH_CFG_FR_BIT         1

// Front Center
#define USB_AUDIO_CH_CFG_FC_BIT         2

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_BIT        3

// Back Left
#define USB_AUDIO_CH_CFG_BL_BIT         4

// Back Right
#define USB_AUDIO_CH_CFG_BR_BIT         5

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_BIT        6

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_BIT        7

// Back Center
#define USB_AUDIO_CH_CFG_BKC_BIT        8

// Side Left
#define USB_AUDIO_CH_CFG_SL_BIT         9

// Side Right
#define USB_AUDIO_CH_CFG_SR_BIT         10

// Top Center
#define USB_AUDIO_CH_CFG_TC_BIT         11

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_BIT        12

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_BIT        13

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_BIT        14

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_BIT        15

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_BIT        16

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_BIT        17

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_BIT       18

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_BIT       19

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_BIT       20

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_BIT       21

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_BIT        22

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_BIT        23

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_BIT         24

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_BIT        25

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_BIT        26

// Raw Data
#define USB_AUDIO_CH_CFG_RD_BIT         31


// Front Left
#define USB_AUDIO_CH_CFG_FL_BITS        1

// Front Right
#define USB_AUDIO_CH_CFG_FR_BITS        1

// Front Center
#define USB_AUDIO_CH_CFG_FC_BITS        1

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_BITS       1

// Back Left
#define USB_AUDIO_CH_CFG_BL_BITS        1

// Back Right
#define USB_AUDIO_CH_CFG_BR_BITS        1

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_BITS       1

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_BITS       1

// Back Center
#define USB_AUDIO_CH_CFG_BKC_BITS       1

// Side Left
#define USB_AUDIO_CH_CFG_SL_BITS        1

// Side Right
#define USB_AUDIO_CH_CFG_SR_BITS        1

// Top Center
#define USB_AUDIO_CH_CFG_TC_BITS        1

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_BITS       1

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_BITS       1

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_BITS       1

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_BITS       1

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_BITS       1

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_BITS       1

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_BITS      1

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_BITS      1

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_BITS      1

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_BITS      1

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_BITS       1

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_BITS       1

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_BITS        1

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_BITS       1

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_BITS       1

// Raw Data
#define USB_AUDIO_CH_CFG_RD_BITS        1

// Front Left
#define USB_AUDIO_CH_CFG_FL_MASK        ((1U << USB_AUDIO_CH_CFG_FL_BITS)-1)

// Front Right
#define USB_AUDIO_CH_CFG_FR_MASK        ((1U << USB_AUDIO_CH_CFG_FR_BITS)-1)

// Front Center
#define USB_AUDIO_CH_CFG_FC_MASK        ((1U << USB_AUDIO_CH_CFG_FC_BITS)-1)

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_MASK       ((1U << USB_AUDIO_CH_CFG_LFE_BITS)-1)

// Back Left
#define USB_AUDIO_CH_CFG_BL_MASK        ((1U << USB_AUDIO_CH_CFG_BL_BITS)-1)

// Back Right
#define USB_AUDIO_CH_CFG_BR_MASK        ((1U << USB_AUDIO_CH_CFG_BR_BITS)-1)

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_MASK       ((1U << USB_AUDIO_CH_CFG_FLC_BITS)-1)

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_MASK       ((1U << USB_AUDIO_CH_CFG_FRC_BITS)-1)

// Back Center
#define USB_AUDIO_CH_CFG_BKC_MASK       ((1U << USB_AUDIO_CH_CFG_BKC_BITS)-1)

// Side Left
#define USB_AUDIO_CH_CFG_SL_MASK        ((1U << USB_AUDIO_CH_CFG_SL_BITS)-1)

// Side Right
#define USB_AUDIO_CH_CFG_SR_MASK        ((1U << USB_AUDIO_CH_CFG_SR_BITS)-1)

// Top Center
#define USB_AUDIO_CH_CFG_TC_MASK        ((1U << USB_AUDIO_CH_CFG_TC_BITS)-1)

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_MASK       ((1U << USB_AUDIO_CH_CFG_TFL_BITS)-1)

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_MASK       ((1U << USB_AUDIO_CH_CFG_TFC_BITS)-1)

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_MASK       ((1U << USB_AUDIO_CH_CFG_TFR_BITS)-1)

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_MASK       ((1U << USB_AUDIO_CH_CFG_TBL_BITS)-1)

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_MASK       ((1U << USB_AUDIO_CH_CFG_TBC_BITS)-1)

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_MASK       ((1U << USB_AUDIO_CH_CFG_TBR_BITS)-1)

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_MASK      ((1U << USB_AUDIO_CH_CFG_TFLC_BITS)-1)

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_MASK      ((1U << USB_AUDIO_CH_CFG_TFRC_BITS)-1)

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_MASK      ((1U << USB_AUDIO_CH_CFG_LLFE_BITS)-1)

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_MASK      ((1U << USB_AUDIO_CH_CFG_RLFE_BITS)-1)

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_MASK       ((1U << USB_AUDIO_CH_CFG_TSL_BITS)-1)

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_MASK       ((1U << USB_AUDIO_CH_CFG_TSR_BITS)-1)

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_MASK        ((1U << USB_AUDIO_CH_CFG_BC_BITS)-1)

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_MASK       ((1U << USB_AUDIO_CH_CFG_BLC_BITS)-1)

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_MASK       ((1U << USB_AUDIO_CH_CFG_BRC_BITS)-1)

// Raw Data
#define USB_AUDIO_CH_CFG_RD_MASK        ((1U << USB_AUDIO_CH_CFG_RD_BITS)-1)

// Front Left
#define USB_AUDIO_CH_CFG_FL \
    (USB_AUDIO_CH_CFG_FL_MASK << USB_AUDIO_CH_CFG_FL_BIT)

// Front Right
#define USB_AUDIO_CH_CFG_FR \
    (USB_AUDIO_CH_CFG_FR_MASK << USB_AUDIO_CH_CFG_FR_BIT)

// Front Center
#define USB_AUDIO_CH_CFG_FC \
    (USB_AUDIO_CH_CFG_FC_MASK << USB_AUDIO_CH_CFG_FC_BIT)

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE \
    (USB_AUDIO_CH_CFG_LFE_MASK << USB_AUDIO_CH_CFG_LFE_BIT)

// Back Left
#define USB_AUDIO_CH_CFG_BL \
    (USB_AUDIO_CH_CFG_BL_MASK << USB_AUDIO_CH_CFG_BL_BIT)

// Back Right
#define USB_AUDIO_CH_CFG_BR \
    (USB_AUDIO_CH_CFG_BR_MASK << USB_AUDIO_CH_CFG_BR_BIT)

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC \
    (USB_AUDIO_CH_CFG_FLC_MASK << USB_AUDIO_CH_CFG_FLC_BIT)

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC \
    (USB_AUDIO_CH_CFG_FRC_MASK << USB_AUDIO_CH_CFG_FRC_BIT)

// Back Center
#define USB_AUDIO_CH_CFG_BKC \
    (USB_AUDIO_CH_CFG_BKC_MASK << USB_AUDIO_CH_CFG_BKC_BIT)

// Side Left
#define USB_AUDIO_CH_CFG_SL \
    (USB_AUDIO_CH_CFG_SL_MASK << USB_AUDIO_CH_CFG_SL_BIT)

// Side Right
#define USB_AUDIO_CH_CFG_SR \
    (USB_AUDIO_CH_CFG_SR_MASK << USB_AUDIO_CH_CFG_SR_BIT)

// Top Center
#define USB_AUDIO_CH_CFG_TC \
    (USB_AUDIO_CH_CFG_TC_MASK << USB_AUDIO_CH_CFG_TC_BIT)

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL \
    (USB_AUDIO_CH_CFG_TFL_MASK << USB_AUDIO_CH_CFG_TFL_BIT)

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC \
    (USB_AUDIO_CH_CFG_TFC_MASK << USB_AUDIO_CH_CFG_TFC_BIT)

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR \
    (USB_AUDIO_CH_CFG_TFR_MASK << USB_AUDIO_CH_CFG_TFR_BIT)

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL \
    (USB_AUDIO_CH_CFG_TBL_MASK << USB_AUDIO_CH_CFG_TBL_BIT)

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC \
    (USB_AUDIO_CH_CFG_TBC_MASK << USB_AUDIO_CH_CFG_TBC_BIT)

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR \
    (USB_AUDIO_CH_CFG_TBR_MASK << USB_AUDIO_CH_CFG_TBR_BIT)

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC \
    (USB_AUDIO_CH_CFG_TFLC_MASK << USB_AUDIO_CH_CFG_TFLC_BIT)

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC \
    (USB_AUDIO_CH_CFG_TFRC_MASK << USB_AUDIO_CH_CFG_TFRC_BIT)

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE \
    (USB_AUDIO_CH_CFG_LLFE_MASK << USB_AUDIO_CH_CFG_LLFE_BIT)

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE \
    (USB_AUDIO_CH_CFG_RLFE_MASK << USB_AUDIO_CH_CFG_RLFE_BIT)

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL \
    (USB_AUDIO_CH_CFG_TSL_MASK << USB_AUDIO_CH_CFG_TSL_BIT)

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR \
    (USB_AUDIO_CH_CFG_TSR_MASK << USB_AUDIO_CH_CFG_TSR_BIT)

// Bottom Center
#define USB_AUDIO_CH_CFG_BC \
    (USB_AUDIO_CH_CFG_BC_MASK << USB_AUDIO_CH_CFG_BC_BIT)

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC \
    (USB_AUDIO_CH_CFG_BLC_MASK << USB_AUDIO_CH_CFG_BLC_BIT)

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC \
    (USB_AUDIO_CH_CFG_BRC_MASK << USB_AUDIO_CH_CFG_BRC_BIT)

// Raw Data
#define USB_AUDIO_CH_CFG_RD \
    (USB_AUDIO_CH_CFG_RD_MASK << USB_AUDIO_CH_CFG_RD_BIT)


// Front Left
#define USB_AUDIO_CH_CFG_FL_n(n)        ((n) << USB_AUDIO_CH_CFG_FL_BIT)

// Front Right
#define USB_AUDIO_CH_CFG_FR_n(n)        ((n) << USB_AUDIO_CH_CFG_FR_BIT)

// Front Center
#define USB_AUDIO_CH_CFG_FC_n(n)        ((n) << USB_AUDIO_CH_CFG_FC_BIT)

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_n(n)       ((n) << USB_AUDIO_CH_CFG_LFE_BIT)

// Back Left
#define USB_AUDIO_CH_CFG_BL_n(n)        ((n) << USB_AUDIO_CH_CFG_BL_BIT)

// Back Right
#define USB_AUDIO_CH_CFG_BR_n(n)        ((n) << USB_AUDIO_CH_CFG_BR_BIT)

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_n(n)       ((n) << USB_AUDIO_CH_CFG_FLC_BIT)

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_n(n)       ((n) << USB_AUDIO_CH_CFG_FRC_BIT)

// Back Center
#define USB_AUDIO_CH_CFG_BKC_n(n)       ((n) << USB_AUDIO_CH_CFG_BKC_BIT)

// Side Left
#define USB_AUDIO_CH_CFG_SL_n(n)        ((n) << USB_AUDIO_CH_CFG_SL_BIT)

// Side Right
#define USB_AUDIO_CH_CFG_SR_n(n)        ((n) << USB_AUDIO_CH_CFG_SR_BIT)

// Top Center
#define USB_AUDIO_CH_CFG_TC_n(n)        ((n) << USB_AUDIO_CH_CFG_TC_BIT)

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_n(n)       ((n) << USB_AUDIO_CH_CFG_TFL_BIT)

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_n(n)       ((n) << USB_AUDIO_CH_CFG_TFC_BIT)

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_n(n)       ((n) << USB_AUDIO_CH_CFG_TFR_BIT)

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_n(n)       ((n) << USB_AUDIO_CH_CFG_TBL_BIT)

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_n(n)       ((n) << USB_AUDIO_CH_CFG_TBC_BIT)

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_n(n)       ((n) << USB_AUDIO_CH_CFG_TBR_BIT)

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_n(n)      ((n) << USB_AUDIO_CH_CFG_TFLC_BIT)

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_n(n)      ((n) << USB_AUDIO_CH_CFG_TFRC_BIT)

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_n(n)      ((n) << USB_AUDIO_CH_CFG_LLFE_BIT)

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_n(n)      ((n) << USB_AUDIO_CH_CFG_RLFE_BIT)

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_n(n)       ((n) << USB_AUDIO_CH_CFG_TSL_BIT)

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_n(n)       ((n) << USB_AUDIO_CH_CFG_TSR_BIT)

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_n(n)        ((n) << USB_AUDIO_CH_CFG_BC_BIT)

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_n(n)       ((n) << USB_AUDIO_CH_CFG_BLC_BIT)

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_n(n)       ((n) << USB_AUDIO_CH_CFG_BRC_BIT)

// Raw Data
#define USB_AUDIO_CH_CFG_RD_n(n)        ((n) << USB_AUDIO_CH_CFG_RD_BIT)


// Front Left
#define USB_AUDIO_CH_CFG_FL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_FL_BIT) & USB_AUDIO_CH_CFG_FL_MASK)

// Front Right
#define USB_AUDIO_CH_CFG_FR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_FR_BIT) & USB_AUDIO_CH_CFG_FR_MASK)

// Front Center
#define USB_AUDIO_CH_CFG_FC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_FC_BIT) & USB_AUDIO_CH_CFG_FC_MASK)

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_LFE_BIT) & USB_AUDIO_CH_CFG_LFE_MASK)

// Back Left
#define USB_AUDIO_CH_CFG_BL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BL_BIT) & USB_AUDIO_CH_CFG_BL_MASK)

// Back Right
#define USB_AUDIO_CH_CFG_BR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BR_BIT) & USB_AUDIO_CH_CFG_BR_MASK)

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_FLC_BIT) & USB_AUDIO_CH_CFG_FLC_MASK)

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_FRC_BIT) & USB_AUDIO_CH_CFG_FRC_MASK)

// Back Center
#define USB_AUDIO_CH_CFG_BKC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BKC_BIT) & USB_AUDIO_CH_CFG_BKC_MASK)

// Side Left
#define USB_AUDIO_CH_CFG_SL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_SL_BIT) & USB_AUDIO_CH_CFG_SL_MASK)

// Side Right
#define USB_AUDIO_CH_CFG_SR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_SR_BIT) & USB_AUDIO_CH_CFG_SR_MASK)

// Top Center
#define USB_AUDIO_CH_CFG_TC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TC_BIT) & USB_AUDIO_CH_CFG_TC_MASK)

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TFL_BIT) & USB_AUDIO_CH_CFG_TFL_MASK)

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TFC_BIT) & USB_AUDIO_CH_CFG_TFC_MASK)

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TFR_BIT) & USB_AUDIO_CH_CFG_TFR_MASK)

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TBL_BIT) & USB_AUDIO_CH_CFG_TBL_MASK)

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TBC_BIT) & USB_AUDIO_CH_CFG_TBC_MASK)

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TBR_BIT) & USB_AUDIO_CH_CFG_TBR_MASK)

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TFLC_BIT) & USB_AUDIO_CH_CFG_TFLC_MASK)

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TFRC_BIT) & USB_AUDIO_CH_CFG_TFRC_MASK)

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_LLFE_BIT) & USB_AUDIO_CH_CFG_LLFE_MASK)

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_RLFE_BIT) & USB_AUDIO_CH_CFG_RLFE_MASK)

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TSL_BIT) & USB_AUDIO_CH_CFG_TSL_MASK)

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_TSR_BIT) & USB_AUDIO_CH_CFG_TSR_MASK)

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BC_BIT) & USB_AUDIO_CH_CFG_BC_MASK)

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BLC_BIT) & USB_AUDIO_CH_CFG_BLC_MASK)

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_BRC_BIT) & USB_AUDIO_CH_CFG_BRC_MASK)

// Raw Data
#define USB_AUDIO_CH_CFG_RD_GET(n) \
    (((n) >> USB_AUDIO_CH_CFG_RD_BIT) & USB_AUDIO_CH_CFG_RD_MASK)


// Front Left
#define USB_AUDIO_CH_CFG_FL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_FL) | USB_AUDIO_CH_CFG_FL_n((n)))

// Front Right
#define USB_AUDIO_CH_CFG_FR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_FR) | USB_AUDIO_CH_CFG_FR_n((n)))

// Front Center
#define USB_AUDIO_CH_CFG_FC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_FC) | USB_AUDIO_CH_CFG_FC_n((n)))

// Low Frequency Effects
#define USB_AUDIO_CH_CFG_LFE_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_LFE) | USB_AUDIO_CH_CFG_LFE_n((n)))

// Back Left
#define USB_AUDIO_CH_CFG_BL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BL) | USB_AUDIO_CH_CFG_BL_n((n)))

// Back Right
#define USB_AUDIO_CH_CFG_BR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BR) | USB_AUDIO_CH_CFG_BR_n((n)))

// Front Left of Center
#define USB_AUDIO_CH_CFG_FLC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_FLC) | USB_AUDIO_CH_CFG_FLC_n((n)))

// Front Right of Center
#define USB_AUDIO_CH_CFG_FRC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_FRC) | USB_AUDIO_CH_CFG_FRC_n((n)))

// Back Center
#define USB_AUDIO_CH_CFG_BKC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BKC) | USB_AUDIO_CH_CFG_BKC_n((n)))

// Side Left
#define USB_AUDIO_CH_CFG_SL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_SL) | USB_AUDIO_CH_CFG_SL_n((n)))

// Side Right
#define USB_AUDIO_CH_CFG_SR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_SR) | USB_AUDIO_CH_CFG_SR_n((n)))

// Top Center
#define USB_AUDIO_CH_CFG_TC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TC) | USB_AUDIO_CH_CFG_TC_n((n)))

// Top Front Left
#define USB_AUDIO_CH_CFG_TFL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TFL) | USB_AUDIO_CH_CFG_TFL_n((n)))

// Top Front Center
#define USB_AUDIO_CH_CFG_TFC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TFC) | USB_AUDIO_CH_CFG_TFC_n((n)))

// Top Front Right
#define USB_AUDIO_CH_CFG_TFR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TFR) | USB_AUDIO_CH_CFG_TFR_n((n)))

// Top Back Left
#define USB_AUDIO_CH_CFG_TBL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TBL) | USB_AUDIO_CH_CFG_TBL_n((n)))

// Top Back Center
#define USB_AUDIO_CH_CFG_TBC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TBC) | USB_AUDIO_CH_CFG_TBC_n((n)))

// Top Back Right
#define USB_AUDIO_CH_CFG_TBR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TBR) | USB_AUDIO_CH_CFG_TBR_n((n)))

// Top Front Left of Center
#define USB_AUDIO_CH_CFG_TFLC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TFLC) | USB_AUDIO_CH_CFG_TFLC_n((n)))

// Top Front Right of Center
#define USB_AUDIO_CH_CFG_TFRC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TFRC) | USB_AUDIO_CH_CFG_TFRC_n((n)))

// Left Low Frequency Effects
#define USB_AUDIO_CH_CFG_LLFE_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_LLFE) | USB_AUDIO_CH_CFG_LLFE_n((n)))

// Right Low Frequency Effects
#define USB_AUDIO_CH_CFG_RLFE_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_RLFE) | USB_AUDIO_CH_CFG_RLFE_n((n)))

// Top Side Left
#define USB_AUDIO_CH_CFG_TSL_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TSL) | USB_AUDIO_CH_CFG_TSL_n((n)))

// Top Side Right
#define USB_AUDIO_CH_CFG_TSR_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_TSR) | USB_AUDIO_CH_CFG_TSR_n((n)))

// Bottom Center
#define USB_AUDIO_CH_CFG_BC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BC) | USB_AUDIO_CH_CFG_BC_n((n)))

// Back Left of Center
#define USB_AUDIO_CH_CFG_BLC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BLC) | USB_AUDIO_CH_CFG_BLC_n((n)))

// Back Right of Center
#define USB_AUDIO_CH_CFG_BRC_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_BRC) | USB_AUDIO_CH_CFG_BRC_n((n)))

// Raw Data
#define USB_AUDIO_CH_CFG_RD_SET(r,n) \
    ((r) = ((r) & ~USB_AUDIO_CH_CFG_RD) | USB_AUDIO_CH_CFG_RD_n((n)))

