#!/usr/bin/expect

set timeout -1
set host [lindex $argv 0]
set port [lindex $argv 1]
spawn telnet $host $port
send "\n"
expect "(symsrv) "
foreach cmd [lrange $argv 2 $argc] {
	send "$cmd\n"
	expect "(symsrv) "
}
send "\x1d"
send "close\n"
send_user "\n"

