// THIS FILE IS AUTOMATICALLY GENERATED
// from /home/doug/code/dgos/src/kernel/device/ahci.bits

//
// AHCI_HC_CAP: 3.1.1 HBA capabilities

#define AHCI_HC_CAP_S64A_BIT        31
#define AHCI_HC_CAP_SNCQ_BIT        30
#define AHCI_HC_CAP_SSNTF_BIT       29
#define AHCI_HC_CAP_SMPS_BIT        28
#define AHCI_HC_CAP_SSS_BIT         27
#define AHCI_HC_CAP_SALP_BIT        26
#define AHCI_HC_CAP_SAL_BIT         25
#define AHCI_HC_CAP_SCLO_BIT        24
#define AHCI_HC_CAP_ISS_BIT         20
#define AHCI_HC_CAP_SAM_BIT         18
#define AHCI_HC_CAP_SPM_BIT         17
#define AHCI_HC_CAP_FBSS_BIT        16
#define AHCI_HC_CAP_PMD_BIT         15
#define AHCI_HC_CAP_SSC_BIT         14
#define AHCI_HC_CAP_PSC_BIT         13
#define AHCI_HC_CAP_NCS_BIT         8
#define AHCI_HC_CAP_CCCS_BIT        7
#define AHCI_HC_CAP_EMS_BIT         6
#define AHCI_HC_CAP_SXS_BIT         5
#define AHCI_HC_CAP_NP_BIT          0

#define AHCI_HC_CAP_S64A_BITS       1
#define AHCI_HC_CAP_SNCQ_BITS       1
#define AHCI_HC_CAP_SSNTF_BITS      1
#define AHCI_HC_CAP_SMPS_BITS       1
#define AHCI_HC_CAP_SSS_BITS        1
#define AHCI_HC_CAP_SALP_BITS       1
#define AHCI_HC_CAP_SAL_BITS        1
#define AHCI_HC_CAP_SCLO_BITS       1
#define AHCI_HC_CAP_ISS_BITS        4
#define AHCI_HC_CAP_SAM_BITS        1
#define AHCI_HC_CAP_SPM_BITS        1
#define AHCI_HC_CAP_FBSS_BITS       1
#define AHCI_HC_CAP_PMD_BITS        1
#define AHCI_HC_CAP_SSC_BITS        1
#define AHCI_HC_CAP_PSC_BITS        1
#define AHCI_HC_CAP_NCS_BITS        5
#define AHCI_HC_CAP_CCCS_BITS       1
#define AHCI_HC_CAP_EMS_BITS        1
#define AHCI_HC_CAP_SXS_BITS        1
#define AHCI_HC_CAP_NP_BITS         5
#define AHCI_HC_CAP_S64A_MASK       ((1U << AHCI_HC_CAP_S64A_BITS)-1)
#define AHCI_HC_CAP_SNCQ_MASK       ((1U << AHCI_HC_CAP_SNCQ_BITS)-1)
#define AHCI_HC_CAP_SSNTF_MASK      ((1U << AHCI_HC_CAP_SSNTF_BITS)-1)
#define AHCI_HC_CAP_SMPS_MASK       ((1U << AHCI_HC_CAP_SMPS_BITS)-1)
#define AHCI_HC_CAP_SSS_MASK        ((1U << AHCI_HC_CAP_SSS_BITS)-1)
#define AHCI_HC_CAP_SALP_MASK       ((1U << AHCI_HC_CAP_SALP_BITS)-1)
#define AHCI_HC_CAP_SAL_MASK        ((1U << AHCI_HC_CAP_SAL_BITS)-1)
#define AHCI_HC_CAP_SCLO_MASK       ((1U << AHCI_HC_CAP_SCLO_BITS)-1)
#define AHCI_HC_CAP_ISS_MASK        ((1U << AHCI_HC_CAP_ISS_BITS)-1)
#define AHCI_HC_CAP_SAM_MASK        ((1U << AHCI_HC_CAP_SAM_BITS)-1)
#define AHCI_HC_CAP_SPM_MASK        ((1U << AHCI_HC_CAP_SPM_BITS)-1)
#define AHCI_HC_CAP_FBSS_MASK       ((1U << AHCI_HC_CAP_FBSS_BITS)-1)
#define AHCI_HC_CAP_PMD_MASK        ((1U << AHCI_HC_CAP_PMD_BITS)-1)
#define AHCI_HC_CAP_SSC_MASK        ((1U << AHCI_HC_CAP_SSC_BITS)-1)
#define AHCI_HC_CAP_PSC_MASK        ((1U << AHCI_HC_CAP_PSC_BITS)-1)
#define AHCI_HC_CAP_NCS_MASK        ((1U << AHCI_HC_CAP_NCS_BITS)-1)
#define AHCI_HC_CAP_CCCS_MASK       ((1U << AHCI_HC_CAP_CCCS_BITS)-1)
#define AHCI_HC_CAP_EMS_MASK        ((1U << AHCI_HC_CAP_EMS_BITS)-1)
#define AHCI_HC_CAP_SXS_MASK        ((1U << AHCI_HC_CAP_SXS_BITS)-1)
#define AHCI_HC_CAP_NP_MASK         ((1U << AHCI_HC_CAP_NP_BITS)-1)

// 64 bit capable
#define AHCI_HC_CAP_S64A \
    (AHCI_HC_CAP_S64A_MASK << AHCI_HC_CAP_S64A_BIT)

// Supports native command queuing
#define AHCI_HC_CAP_SNCQ \
    (AHCI_HC_CAP_SNCQ_MASK << AHCI_HC_CAP_SNCQ_BIT)

// Supports SNotification register
#define AHCI_HC_CAP_SSNTF \
    (AHCI_HC_CAP_SSNTF_MASK << AHCI_HC_CAP_SSNTF_BIT)

// Supports mechanical presence switch
#define AHCI_HC_CAP_SMPS \
    (AHCI_HC_CAP_SMPS_MASK << AHCI_HC_CAP_SMPS_BIT)

// Supports staggered spinup
#define AHCI_HC_CAP_SSS \
    (AHCI_HC_CAP_SSS_MASK << AHCI_HC_CAP_SSS_BIT)

// Supports aggressive link power management
#define AHCI_HC_CAP_SALP \
    (AHCI_HC_CAP_SALP_MASK << AHCI_HC_CAP_SALP_BIT)

// Supports activity LED
#define AHCI_HC_CAP_SAL \
    (AHCI_HC_CAP_SAL_MASK << AHCI_HC_CAP_SAL_BIT)

// Supports command list override
#define AHCI_HC_CAP_SCLO \
    (AHCI_HC_CAP_SCLO_MASK << AHCI_HC_CAP_SCLO_BIT)

// Interface speed support
#define AHCI_HC_CAP_ISS \
    (AHCI_HC_CAP_ISS_MASK << AHCI_HC_CAP_ISS_BIT)

// Supports ACHI mode only
#define AHCI_HC_CAP_SAM \
    (AHCI_HC_CAP_SAM_MASK << AHCI_HC_CAP_SAM_BIT)

// Supports port multiplier
#define AHCI_HC_CAP_SPM \
    (AHCI_HC_CAP_SPM_MASK << AHCI_HC_CAP_SPM_BIT)

// FIS based switching support
#define AHCI_HC_CAP_FBSS \
    (AHCI_HC_CAP_FBSS_MASK << AHCI_HC_CAP_FBSS_BIT)

// PIO multiple DRQ block
#define AHCI_HC_CAP_PMD \
    (AHCI_HC_CAP_PMD_MASK << AHCI_HC_CAP_PMD_BIT)

// Slumber state capable
#define AHCI_HC_CAP_SSC \
    (AHCI_HC_CAP_SSC_MASK << AHCI_HC_CAP_SSC_BIT)

// Partial state capable
#define AHCI_HC_CAP_PSC \
    (AHCI_HC_CAP_PSC_MASK << AHCI_HC_CAP_PSC_BIT)

// Number of command slots
#define AHCI_HC_CAP_NCS \
    (AHCI_HC_CAP_NCS_MASK << AHCI_HC_CAP_NCS_BIT)

// Command completion coalescing supported
#define AHCI_HC_CAP_CCCS \
    (AHCI_HC_CAP_CCCS_MASK << AHCI_HC_CAP_CCCS_BIT)

// Enclosure management supported
#define AHCI_HC_CAP_EMS \
    (AHCI_HC_CAP_EMS_MASK << AHCI_HC_CAP_EMS_BIT)

// Supports eXternal SATA
#define AHCI_HC_CAP_SXS \
    (AHCI_HC_CAP_SXS_MASK << AHCI_HC_CAP_SXS_BIT)

// Number of ports
#define AHCI_HC_CAP_NP              (AHCI_HC_CAP_NP_MASK << AHCI_HC_CAP_NP_BIT)

#define AHCI_HC_CAP_S64A_n(n)       ((n) << AHCI_HC_CAP_S64A_BIT)
#define AHCI_HC_CAP_SNCQ_n(n)       ((n) << AHCI_HC_CAP_SNCQ_BIT)
#define AHCI_HC_CAP_SSNTF_n(n)      ((n) << AHCI_HC_CAP_SSNTF_BIT)
#define AHCI_HC_CAP_SMPS_n(n)       ((n) << AHCI_HC_CAP_SMPS_BIT)
#define AHCI_HC_CAP_SSS_n(n)        ((n) << AHCI_HC_CAP_SSS_BIT)
#define AHCI_HC_CAP_SALP_n(n)       ((n) << AHCI_HC_CAP_SALP_BIT)
#define AHCI_HC_CAP_SAL_n(n)        ((n) << AHCI_HC_CAP_SAL_BIT)
#define AHCI_HC_CAP_SCLO_n(n)       ((n) << AHCI_HC_CAP_SCLO_BIT)
#define AHCI_HC_CAP_ISS_n(n)        ((n) << AHCI_HC_CAP_ISS_BIT)
#define AHCI_HC_CAP_SAM_n(n)        ((n) << AHCI_HC_CAP_SAM_BIT)
#define AHCI_HC_CAP_SPM_n(n)        ((n) << AHCI_HC_CAP_SPM_BIT)
#define AHCI_HC_CAP_FBSS_n(n)       ((n) << AHCI_HC_CAP_FBSS_BIT)
#define AHCI_HC_CAP_PMD_n(n)        ((n) << AHCI_HC_CAP_PMD_BIT)
#define AHCI_HC_CAP_SSC_n(n)        ((n) << AHCI_HC_CAP_SSC_BIT)
#define AHCI_HC_CAP_PSC_n(n)        ((n) << AHCI_HC_CAP_PSC_BIT)
#define AHCI_HC_CAP_NCS_n(n)        ((n) << AHCI_HC_CAP_NCS_BIT)
#define AHCI_HC_CAP_CCCS_n(n)       ((n) << AHCI_HC_CAP_CCCS_BIT)
#define AHCI_HC_CAP_EMS_n(n)        ((n) << AHCI_HC_CAP_EMS_BIT)
#define AHCI_HC_CAP_SXS_n(n)        ((n) << AHCI_HC_CAP_SXS_BIT)
#define AHCI_HC_CAP_NP_n(n)         ((n) << AHCI_HC_CAP_NP_BIT)

#define AHCI_HC_CAP_S64A_GET(n) \
    (((n) >> AHCI_HC_CAP_S64A_BIT) & AHCI_HC_CAP_S64A_MASK)
#define AHCI_HC_CAP_SNCQ_GET(n) \
    (((n) >> AHCI_HC_CAP_SNCQ_BIT) & AHCI_HC_CAP_SNCQ_MASK)
#define AHCI_HC_CAP_SSNTF_GET(n) \
    (((n) >> AHCI_HC_CAP_SSNTF_BIT) & AHCI_HC_CAP_SSNTF_MASK)
#define AHCI_HC_CAP_SMPS_GET(n) \
    (((n) >> AHCI_HC_CAP_SMPS_BIT) & AHCI_HC_CAP_SMPS_MASK)
#define AHCI_HC_CAP_SSS_GET(n) \
    (((n) >> AHCI_HC_CAP_SSS_BIT) & AHCI_HC_CAP_SSS_MASK)
#define AHCI_HC_CAP_SALP_GET(n) \
    (((n) >> AHCI_HC_CAP_SALP_BIT) & AHCI_HC_CAP_SALP_MASK)
#define AHCI_HC_CAP_SAL_GET(n) \
    (((n) >> AHCI_HC_CAP_SAL_BIT) & AHCI_HC_CAP_SAL_MASK)
#define AHCI_HC_CAP_SCLO_GET(n) \
    (((n) >> AHCI_HC_CAP_SCLO_BIT) & AHCI_HC_CAP_SCLO_MASK)
#define AHCI_HC_CAP_ISS_GET(n) \
    (((n) >> AHCI_HC_CAP_ISS_BIT) & AHCI_HC_CAP_ISS_MASK)
#define AHCI_HC_CAP_SAM_GET(n) \
    (((n) >> AHCI_HC_CAP_SAM_BIT) & AHCI_HC_CAP_SAM_MASK)
#define AHCI_HC_CAP_SPM_GET(n) \
    (((n) >> AHCI_HC_CAP_SPM_BIT) & AHCI_HC_CAP_SPM_MASK)
#define AHCI_HC_CAP_FBSS_GET(n) \
    (((n) >> AHCI_HC_CAP_FBSS_BIT) & AHCI_HC_CAP_FBSS_MASK)
#define AHCI_HC_CAP_PMD_GET(n) \
    (((n) >> AHCI_HC_CAP_PMD_BIT) & AHCI_HC_CAP_PMD_MASK)
#define AHCI_HC_CAP_SSC_GET(n) \
    (((n) >> AHCI_HC_CAP_SSC_BIT) & AHCI_HC_CAP_SSC_MASK)
#define AHCI_HC_CAP_PSC_GET(n) \
    (((n) >> AHCI_HC_CAP_PSC_BIT) & AHCI_HC_CAP_PSC_MASK)
#define AHCI_HC_CAP_NCS_GET(n) \
    (((n) >> AHCI_HC_CAP_NCS_BIT) & AHCI_HC_CAP_NCS_MASK)
#define AHCI_HC_CAP_CCCS_GET(n) \
    (((n) >> AHCI_HC_CAP_CCCS_BIT) & AHCI_HC_CAP_CCCS_MASK)
#define AHCI_HC_CAP_EMS_GET(n) \
    (((n) >> AHCI_HC_CAP_EMS_BIT) & AHCI_HC_CAP_EMS_MASK)
#define AHCI_HC_CAP_SXS_GET(n) \
    (((n) >> AHCI_HC_CAP_SXS_BIT) & AHCI_HC_CAP_SXS_MASK)
#define AHCI_HC_CAP_NP_GET(n) \
    (((n) >> AHCI_HC_CAP_NP_BIT) & AHCI_HC_CAP_NP_MASK)

#define AHCI_HC_CAP_S64A_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_S64A) | AHCI_HC_CAP_S64A_n((n)))
#define AHCI_HC_CAP_SNCQ_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SNCQ) | AHCI_HC_CAP_SNCQ_n((n)))
#define AHCI_HC_CAP_SSNTF_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SSNTF) | AHCI_HC_CAP_SSNTF_n((n)))
#define AHCI_HC_CAP_SMPS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SMPS) | AHCI_HC_CAP_SMPS_n((n)))
#define AHCI_HC_CAP_SSS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SSS) | AHCI_HC_CAP_SSS_n((n)))
#define AHCI_HC_CAP_SALP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SALP) | AHCI_HC_CAP_SALP_n((n)))
#define AHCI_HC_CAP_SAL_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SAL) | AHCI_HC_CAP_SAL_n((n)))
#define AHCI_HC_CAP_SCLO_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SCLO) | AHCI_HC_CAP_SCLO_n((n)))
#define AHCI_HC_CAP_ISS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_ISS) | AHCI_HC_CAP_ISS_n((n)))
#define AHCI_HC_CAP_SAM_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SAM) | AHCI_HC_CAP_SAM_n((n)))
#define AHCI_HC_CAP_SPM_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SPM) | AHCI_HC_CAP_SPM_n((n)))
#define AHCI_HC_CAP_FBSS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_FBSS) | AHCI_HC_CAP_FBSS_n((n)))
#define AHCI_HC_CAP_PMD_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_PMD) | AHCI_HC_CAP_PMD_n((n)))
#define AHCI_HC_CAP_SSC_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SSC) | AHCI_HC_CAP_SSC_n((n)))
#define AHCI_HC_CAP_PSC_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_PSC) | AHCI_HC_CAP_PSC_n((n)))
#define AHCI_HC_CAP_NCS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_NCS) | AHCI_HC_CAP_NCS_n((n)))
#define AHCI_HC_CAP_CCCS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_CCCS) | AHCI_HC_CAP_CCCS_n((n)))
#define AHCI_HC_CAP_EMS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_EMS) | AHCI_HC_CAP_EMS_n((n)))
#define AHCI_HC_CAP_SXS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_SXS) | AHCI_HC_CAP_SXS_n((n)))
#define AHCI_HC_CAP_NP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_CAP_NP) | AHCI_HC_CAP_NP_n((n)))

//
// AHCI_HC_HC: 3.1.2 Global HBA control

#define AHCI_HC_HC_AE_BIT         31
#define AHCI_HC_HC_MRSM_BIT       2
#define AHCI_HC_HC_IE_BIT         1
#define AHCI_HC_HC_HR_BIT         0

#define AHCI_HC_HC_AE_BITS        1
#define AHCI_HC_HC_MRSM_BITS      1
#define AHCI_HC_HC_IE_BITS        1
#define AHCI_HC_HC_HR_BITS        1
#define AHCI_HC_HC_AE_MASK        ((1U << AHCI_HC_HC_AE_BITS)-1)
#define AHCI_HC_HC_MRSM_MASK      ((1U << AHCI_HC_HC_MRSM_BITS)-1)
#define AHCI_HC_HC_IE_MASK        ((1U << AHCI_HC_HC_IE_BITS)-1)
#define AHCI_HC_HC_HR_MASK        ((1U << AHCI_HC_HC_HR_BITS)-1)

// AHCI enable
#define AHCI_HC_HC_AE             (AHCI_HC_HC_AE_MASK << AHCI_HC_HC_AE_BIT)

// MSI revert to single message
#define AHCI_HC_HC_MRSM           (AHCI_HC_HC_MRSM_MASK << AHCI_HC_HC_MRSM_BIT)

// Interrupt enable
#define AHCI_HC_HC_IE             (AHCI_HC_HC_IE_MASK << AHCI_HC_HC_IE_BIT)

// HBA reset
#define AHCI_HC_HC_HR             (AHCI_HC_HC_HR_MASK << AHCI_HC_HC_HR_BIT)

#define AHCI_HC_HC_AE_n(n)        ((n) << AHCI_HC_HC_AE_BIT)
#define AHCI_HC_HC_MRSM_n(n)      ((n) << AHCI_HC_HC_MRSM_BIT)
#define AHCI_HC_HC_IE_n(n)        ((n) << AHCI_HC_HC_IE_BIT)
#define AHCI_HC_HC_HR_n(n)        ((n) << AHCI_HC_HC_HR_BIT)

#define AHCI_HC_HC_AE_GET(n) \
    (((n) >> AHCI_HC_HC_AE_BIT) & AHCI_HC_HC_AE_MASK)
#define AHCI_HC_HC_MRSM_GET(n) \
    (((n) >> AHCI_HC_HC_MRSM_BIT) & AHCI_HC_HC_MRSM_MASK)
#define AHCI_HC_HC_IE_GET(n) \
    (((n) >> AHCI_HC_HC_IE_BIT) & AHCI_HC_HC_IE_MASK)
#define AHCI_HC_HC_HR_GET(n) \
    (((n) >> AHCI_HC_HC_HR_BIT) & AHCI_HC_HC_HR_MASK)

#define AHCI_HC_HC_AE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_HC_AE) | AHCI_HC_HC_AE_n((n)))
#define AHCI_HC_HC_MRSM_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_HC_MRSM) | AHCI_HC_HC_MRSM_n((n)))
#define AHCI_HC_HC_IE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_HC_IE) | AHCI_HC_HC_IE_n((n)))
#define AHCI_HC_HC_HR_SET(r,n) \
    ((r) = ((r) & ~AHCI_HC_HC_HR) | AHCI_HC_HC_HR_n((n)))

//
// AHCI_HP_IS: 3.3.5 PxIS Port interrupt status

#define AHCI_HP_IS_CPDS_BIT       31
#define AHCI_HP_IS_TFES_BIT       30
#define AHCI_HP_IS_HBFS_BIT       29
#define AHCI_HP_IS_HBDS_BIT       28
#define AHCI_HP_IS_IFS_BIT        27
#define AHCI_HP_IS_INFS_BIT       26
#define AHCI_HP_IS_OFS_BIT        24
#define AHCI_HP_IS_IPMS_BIT       23
#define AHCI_HP_IS_PRCS_BIT       22
#define AHCI_HP_IS_DMPS_BIT       7
#define AHCI_HP_IS_PCS_BIT        6
#define AHCI_HP_IS_DPS_BIT        5
#define AHCI_HP_IS_UFS_BIT        4
#define AHCI_HP_IS_SDBS_BIT       3
#define AHCI_HP_IS_DSS_BIT        2
#define AHCI_HP_IS_PSS_BIT        1
#define AHCI_HP_IS_DHRS_BIT       0

#define AHCI_HP_IS_CPDS_BITS      1
#define AHCI_HP_IS_TFES_BITS      1
#define AHCI_HP_IS_HBFS_BITS      1
#define AHCI_HP_IS_HBDS_BITS      1
#define AHCI_HP_IS_IFS_BITS       1
#define AHCI_HP_IS_INFS_BITS      1
#define AHCI_HP_IS_OFS_BITS       1
#define AHCI_HP_IS_IPMS_BITS      1
#define AHCI_HP_IS_PRCS_BITS      1
#define AHCI_HP_IS_DMPS_BITS      1
#define AHCI_HP_IS_PCS_BITS       1
#define AHCI_HP_IS_DPS_BITS       1
#define AHCI_HP_IS_UFS_BITS       1
#define AHCI_HP_IS_SDBS_BITS      1
#define AHCI_HP_IS_DSS_BITS       1
#define AHCI_HP_IS_PSS_BITS       1
#define AHCI_HP_IS_DHRS_BITS      1
#define AHCI_HP_IS_CPDS_MASK      ((1U << AHCI_HP_IS_CPDS_BITS)-1)
#define AHCI_HP_IS_TFES_MASK      ((1U << AHCI_HP_IS_TFES_BITS)-1)
#define AHCI_HP_IS_HBFS_MASK      ((1U << AHCI_HP_IS_HBFS_BITS)-1)
#define AHCI_HP_IS_HBDS_MASK      ((1U << AHCI_HP_IS_HBDS_BITS)-1)
#define AHCI_HP_IS_IFS_MASK       ((1U << AHCI_HP_IS_IFS_BITS)-1)
#define AHCI_HP_IS_INFS_MASK      ((1U << AHCI_HP_IS_INFS_BITS)-1)
#define AHCI_HP_IS_OFS_MASK       ((1U << AHCI_HP_IS_OFS_BITS)-1)
#define AHCI_HP_IS_IPMS_MASK      ((1U << AHCI_HP_IS_IPMS_BITS)-1)
#define AHCI_HP_IS_PRCS_MASK      ((1U << AHCI_HP_IS_PRCS_BITS)-1)
#define AHCI_HP_IS_DMPS_MASK      ((1U << AHCI_HP_IS_DMPS_BITS)-1)
#define AHCI_HP_IS_PCS_MASK       ((1U << AHCI_HP_IS_PCS_BITS)-1)
#define AHCI_HP_IS_DPS_MASK       ((1U << AHCI_HP_IS_DPS_BITS)-1)
#define AHCI_HP_IS_UFS_MASK       ((1U << AHCI_HP_IS_UFS_BITS)-1)
#define AHCI_HP_IS_SDBS_MASK      ((1U << AHCI_HP_IS_SDBS_BITS)-1)
#define AHCI_HP_IS_DSS_MASK       ((1U << AHCI_HP_IS_DSS_BITS)-1)
#define AHCI_HP_IS_PSS_MASK       ((1U << AHCI_HP_IS_PSS_BITS)-1)
#define AHCI_HP_IS_DHRS_MASK      ((1U << AHCI_HP_IS_DHRS_BITS)-1)

// (RWC) Cold port presence detect
#define AHCI_HP_IS_CPDS           (AHCI_HP_IS_CPDS_MASK << AHCI_HP_IS_CPDS_BIT)

// (RWC) Task file error status
#define AHCI_HP_IS_TFES           (AHCI_HP_IS_TFES_MASK << AHCI_HP_IS_TFES_BIT)

// (RWC) Host bus fatal error status
#define AHCI_HP_IS_HBFS           (AHCI_HP_IS_HBFS_MASK << AHCI_HP_IS_HBFS_BIT)

// (RWC) Host bus data error status
#define AHCI_HP_IS_HBDS           (AHCI_HP_IS_HBDS_MASK << AHCI_HP_IS_HBDS_BIT)

// (RWC) Interface fatal error status
#define AHCI_HP_IS_IFS            (AHCI_HP_IS_IFS_MASK << AHCI_HP_IS_IFS_BIT)

// (RWC) Interface non-fatal error status
#define AHCI_HP_IS_INFS           (AHCI_HP_IS_INFS_MASK << AHCI_HP_IS_INFS_BIT)

// (RWC) Overflow status
#define AHCI_HP_IS_OFS            (AHCI_HP_IS_OFS_MASK << AHCI_HP_IS_OFS_BIT)

// (RWC) Incorrect port multiplier status
#define AHCI_HP_IS_IPMS           (AHCI_HP_IS_IPMS_MASK << AHCI_HP_IS_IPMS_BIT)

// (RWC) PhyRdy change status
#define AHCI_HP_IS_PRCS           (AHCI_HP_IS_PRCS_MASK << AHCI_HP_IS_PRCS_BIT)

// (RWC) Device mechanical presence detect
#define AHCI_HP_IS_DMPS           (AHCI_HP_IS_DMPS_MASK << AHCI_HP_IS_DMPS_BIT)

// (RO) Port connect status
#define AHCI_HP_IS_PCS            (AHCI_HP_IS_PCS_MASK << AHCI_HP_IS_PCS_BIT)

// (RWC) Descriptor processed
#define AHCI_HP_IS_DPS            (AHCI_HP_IS_DPS_MASK << AHCI_HP_IS_DPS_BIT)

// (RO) Unknown FIS interrupt
#define AHCI_HP_IS_UFS            (AHCI_HP_IS_UFS_MASK << AHCI_HP_IS_UFS_BIT)

// (RWC) Set device bits interrupt
#define AHCI_HP_IS_SDBS           (AHCI_HP_IS_SDBS_MASK << AHCI_HP_IS_SDBS_BIT)

// (RWC) DMA setup FIS interrupt
#define AHCI_HP_IS_DSS            (AHCI_HP_IS_DSS_MASK << AHCI_HP_IS_DSS_BIT)

// (RWC) PIO setup FIS interrupt
#define AHCI_HP_IS_PSS            (AHCI_HP_IS_PSS_MASK << AHCI_HP_IS_PSS_BIT)

// (RWC) D2H FIS interrupt
#define AHCI_HP_IS_DHRS           (AHCI_HP_IS_DHRS_MASK << AHCI_HP_IS_DHRS_BIT)

#define AHCI_HP_IS_CPDS_n(n)      ((n) << AHCI_HP_IS_CPDS_BIT)
#define AHCI_HP_IS_TFES_n(n)      ((n) << AHCI_HP_IS_TFES_BIT)
#define AHCI_HP_IS_HBFS_n(n)      ((n) << AHCI_HP_IS_HBFS_BIT)
#define AHCI_HP_IS_HBDS_n(n)      ((n) << AHCI_HP_IS_HBDS_BIT)
#define AHCI_HP_IS_IFS_n(n)       ((n) << AHCI_HP_IS_IFS_BIT)
#define AHCI_HP_IS_INFS_n(n)      ((n) << AHCI_HP_IS_INFS_BIT)
#define AHCI_HP_IS_OFS_n(n)       ((n) << AHCI_HP_IS_OFS_BIT)
#define AHCI_HP_IS_IPMS_n(n)      ((n) << AHCI_HP_IS_IPMS_BIT)
#define AHCI_HP_IS_PRCS_n(n)      ((n) << AHCI_HP_IS_PRCS_BIT)
#define AHCI_HP_IS_DMPS_n(n)      ((n) << AHCI_HP_IS_DMPS_BIT)
#define AHCI_HP_IS_PCS_n(n)       ((n) << AHCI_HP_IS_PCS_BIT)
#define AHCI_HP_IS_DPS_n(n)       ((n) << AHCI_HP_IS_DPS_BIT)
#define AHCI_HP_IS_UFS_n(n)       ((n) << AHCI_HP_IS_UFS_BIT)
#define AHCI_HP_IS_SDBS_n(n)      ((n) << AHCI_HP_IS_SDBS_BIT)
#define AHCI_HP_IS_DSS_n(n)       ((n) << AHCI_HP_IS_DSS_BIT)
#define AHCI_HP_IS_PSS_n(n)       ((n) << AHCI_HP_IS_PSS_BIT)
#define AHCI_HP_IS_DHRS_n(n)      ((n) << AHCI_HP_IS_DHRS_BIT)

#define AHCI_HP_IS_CPDS_GET(n) \
    (((n) >> AHCI_HP_IS_CPDS_BIT) & AHCI_HP_IS_CPDS_MASK)
#define AHCI_HP_IS_TFES_GET(n) \
    (((n) >> AHCI_HP_IS_TFES_BIT) & AHCI_HP_IS_TFES_MASK)
#define AHCI_HP_IS_HBFS_GET(n) \
    (((n) >> AHCI_HP_IS_HBFS_BIT) & AHCI_HP_IS_HBFS_MASK)
#define AHCI_HP_IS_HBDS_GET(n) \
    (((n) >> AHCI_HP_IS_HBDS_BIT) & AHCI_HP_IS_HBDS_MASK)
#define AHCI_HP_IS_IFS_GET(n) \
    (((n) >> AHCI_HP_IS_IFS_BIT) & AHCI_HP_IS_IFS_MASK)
#define AHCI_HP_IS_INFS_GET(n) \
    (((n) >> AHCI_HP_IS_INFS_BIT) & AHCI_HP_IS_INFS_MASK)
#define AHCI_HP_IS_OFS_GET(n) \
    (((n) >> AHCI_HP_IS_OFS_BIT) & AHCI_HP_IS_OFS_MASK)
#define AHCI_HP_IS_IPMS_GET(n) \
    (((n) >> AHCI_HP_IS_IPMS_BIT) & AHCI_HP_IS_IPMS_MASK)
#define AHCI_HP_IS_PRCS_GET(n) \
    (((n) >> AHCI_HP_IS_PRCS_BIT) & AHCI_HP_IS_PRCS_MASK)
#define AHCI_HP_IS_DMPS_GET(n) \
    (((n) >> AHCI_HP_IS_DMPS_BIT) & AHCI_HP_IS_DMPS_MASK)
#define AHCI_HP_IS_PCS_GET(n) \
    (((n) >> AHCI_HP_IS_PCS_BIT) & AHCI_HP_IS_PCS_MASK)
#define AHCI_HP_IS_DPS_GET(n) \
    (((n) >> AHCI_HP_IS_DPS_BIT) & AHCI_HP_IS_DPS_MASK)
#define AHCI_HP_IS_UFS_GET(n) \
    (((n) >> AHCI_HP_IS_UFS_BIT) & AHCI_HP_IS_UFS_MASK)
#define AHCI_HP_IS_SDBS_GET(n) \
    (((n) >> AHCI_HP_IS_SDBS_BIT) & AHCI_HP_IS_SDBS_MASK)
#define AHCI_HP_IS_DSS_GET(n) \
    (((n) >> AHCI_HP_IS_DSS_BIT) & AHCI_HP_IS_DSS_MASK)
#define AHCI_HP_IS_PSS_GET(n) \
    (((n) >> AHCI_HP_IS_PSS_BIT) & AHCI_HP_IS_PSS_MASK)
#define AHCI_HP_IS_DHRS_GET(n) \
    (((n) >> AHCI_HP_IS_DHRS_BIT) & AHCI_HP_IS_DHRS_MASK)

#define AHCI_HP_IS_CPDS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_CPDS) | AHCI_HP_IS_CPDS_n((n)))
#define AHCI_HP_IS_TFES_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_TFES) | AHCI_HP_IS_TFES_n((n)))
#define AHCI_HP_IS_HBFS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_HBFS) | AHCI_HP_IS_HBFS_n((n)))
#define AHCI_HP_IS_HBDS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_HBDS) | AHCI_HP_IS_HBDS_n((n)))
#define AHCI_HP_IS_IFS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_IFS) | AHCI_HP_IS_IFS_n((n)))
#define AHCI_HP_IS_INFS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_INFS) | AHCI_HP_IS_INFS_n((n)))
#define AHCI_HP_IS_OFS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_OFS) | AHCI_HP_IS_OFS_n((n)))
#define AHCI_HP_IS_IPMS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_IPMS) | AHCI_HP_IS_IPMS_n((n)))
#define AHCI_HP_IS_PRCS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_PRCS) | AHCI_HP_IS_PRCS_n((n)))
#define AHCI_HP_IS_DMPS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_DMPS) | AHCI_HP_IS_DMPS_n((n)))
#define AHCI_HP_IS_PCS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_PCS) | AHCI_HP_IS_PCS_n((n)))
#define AHCI_HP_IS_DPS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_DPS) | AHCI_HP_IS_DPS_n((n)))
#define AHCI_HP_IS_UFS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_UFS) | AHCI_HP_IS_UFS_n((n)))
#define AHCI_HP_IS_SDBS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_SDBS) | AHCI_HP_IS_SDBS_n((n)))
#define AHCI_HP_IS_DSS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_DSS) | AHCI_HP_IS_DSS_n((n)))
#define AHCI_HP_IS_PSS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_PSS) | AHCI_HP_IS_PSS_n((n)))
#define AHCI_HP_IS_DHRS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IS_DHRS) | AHCI_HP_IS_DHRS_n((n)))

//
// AHCI_HP_IE: 3.3.6 Port intrerupt enable

#define AHCI_HP_IE_CPDE_BIT       31
#define AHCI_HP_IE_TFEE_BIT       30
#define AHCI_HP_IE_HBFE_BIT       29
#define AHCI_HP_IE_HBDE_BIT       28
#define AHCI_HP_IE_IFE_BIT        27
#define AHCI_HP_IE_INFE_BIT       26
#define AHCI_HP_IE_OFE_BIT        24
#define AHCI_HP_IE_IPME_BIT       23
#define AHCI_HP_IE_PRCE_BIT       22
#define AHCI_HP_IE_DMPE_BIT       7
#define AHCI_HP_IE_PCE_BIT        6
#define AHCI_HP_IE_DPE_BIT        5
#define AHCI_HP_IE_UFE_BIT        4
#define AHCI_HP_IE_SDBE_BIT       3
#define AHCI_HP_IE_DSE_BIT        2
#define AHCI_HP_IE_PSE_BIT        1
#define AHCI_HP_IE_DHRE_BIT       0

#define AHCI_HP_IE_CPDE_BITS      1
#define AHCI_HP_IE_TFEE_BITS      1
#define AHCI_HP_IE_HBFE_BITS      1
#define AHCI_HP_IE_HBDE_BITS      1
#define AHCI_HP_IE_IFE_BITS       1
#define AHCI_HP_IE_INFE_BITS      1
#define AHCI_HP_IE_OFE_BITS       1
#define AHCI_HP_IE_IPME_BITS      1
#define AHCI_HP_IE_PRCE_BITS      1
#define AHCI_HP_IE_DMPE_BITS      1
#define AHCI_HP_IE_PCE_BITS       1
#define AHCI_HP_IE_DPE_BITS       1
#define AHCI_HP_IE_UFE_BITS       1
#define AHCI_HP_IE_SDBE_BITS      1
#define AHCI_HP_IE_DSE_BITS       1
#define AHCI_HP_IE_PSE_BITS       1
#define AHCI_HP_IE_DHRE_BITS      1
#define AHCI_HP_IE_CPDE_MASK      ((1U << AHCI_HP_IE_CPDE_BITS)-1)
#define AHCI_HP_IE_TFEE_MASK      ((1U << AHCI_HP_IE_TFEE_BITS)-1)
#define AHCI_HP_IE_HBFE_MASK      ((1U << AHCI_HP_IE_HBFE_BITS)-1)
#define AHCI_HP_IE_HBDE_MASK      ((1U << AHCI_HP_IE_HBDE_BITS)-1)
#define AHCI_HP_IE_IFE_MASK       ((1U << AHCI_HP_IE_IFE_BITS)-1)
#define AHCI_HP_IE_INFE_MASK      ((1U << AHCI_HP_IE_INFE_BITS)-1)
#define AHCI_HP_IE_OFE_MASK       ((1U << AHCI_HP_IE_OFE_BITS)-1)
#define AHCI_HP_IE_IPME_MASK      ((1U << AHCI_HP_IE_IPME_BITS)-1)
#define AHCI_HP_IE_PRCE_MASK      ((1U << AHCI_HP_IE_PRCE_BITS)-1)
#define AHCI_HP_IE_DMPE_MASK      ((1U << AHCI_HP_IE_DMPE_BITS)-1)
#define AHCI_HP_IE_PCE_MASK       ((1U << AHCI_HP_IE_PCE_BITS)-1)
#define AHCI_HP_IE_DPE_MASK       ((1U << AHCI_HP_IE_DPE_BITS)-1)
#define AHCI_HP_IE_UFE_MASK       ((1U << AHCI_HP_IE_UFE_BITS)-1)
#define AHCI_HP_IE_SDBE_MASK      ((1U << AHCI_HP_IE_SDBE_BITS)-1)
#define AHCI_HP_IE_DSE_MASK       ((1U << AHCI_HP_IE_DSE_BITS)-1)
#define AHCI_HP_IE_PSE_MASK       ((1U << AHCI_HP_IE_PSE_BITS)-1)
#define AHCI_HP_IE_DHRE_MASK      ((1U << AHCI_HP_IE_DHRE_BITS)-1)

// (RW/RO) Cold port presence detect enable
#define AHCI_HP_IE_CPDE           (AHCI_HP_IE_CPDE_MASK << AHCI_HP_IE_CPDE_BIT)

// (RW) Task file error status enable
#define AHCI_HP_IE_TFEE           (AHCI_HP_IE_TFEE_MASK << AHCI_HP_IE_TFEE_BIT)

// (RW) Host bus fatal error status enable
#define AHCI_HP_IE_HBFE           (AHCI_HP_IE_HBFE_MASK << AHCI_HP_IE_HBFE_BIT)

// (RW) Host bus data error status enable
#define AHCI_HP_IE_HBDE           (AHCI_HP_IE_HBDE_MASK << AHCI_HP_IE_HBDE_BIT)

// (RW) Interface fatal error status enable
#define AHCI_HP_IE_IFE            (AHCI_HP_IE_IFE_MASK << AHCI_HP_IE_IFE_BIT)

// (RW) Interface non-fatal error status enable
#define AHCI_HP_IE_INFE           (AHCI_HP_IE_INFE_MASK << AHCI_HP_IE_INFE_BIT)

// (RW) Overflow status enable
#define AHCI_HP_IE_OFE            (AHCI_HP_IE_OFE_MASK << AHCI_HP_IE_OFE_BIT)

// (RW) Incorrect port multiplier status enable
#define AHCI_HP_IE_IPME           (AHCI_HP_IE_IPME_MASK << AHCI_HP_IE_IPME_BIT)

// (RW) PhyRdy change status enable
#define AHCI_HP_IE_PRCE           (AHCI_HP_IE_PRCE_MASK << AHCI_HP_IE_PRCE_BIT)

// (RW/RO) Device mechanical presence detect enable
#define AHCI_HP_IE_DMPE           (AHCI_HP_IE_DMPE_MASK << AHCI_HP_IE_DMPE_BIT)

// (RO) Port connect status enable
#define AHCI_HP_IE_PCE            (AHCI_HP_IE_PCE_MASK << AHCI_HP_IE_PCE_BIT)

// (RW) Descriptor processed enable
#define AHCI_HP_IE_DPE            (AHCI_HP_IE_DPE_MASK << AHCI_HP_IE_DPE_BIT)

// (RW) Unknown FIS interrupt enable
#define AHCI_HP_IE_UFE            (AHCI_HP_IE_UFE_MASK << AHCI_HP_IE_UFE_BIT)

// (RW) Set device bits interrupt enable
#define AHCI_HP_IE_SDBE           (AHCI_HP_IE_SDBE_MASK << AHCI_HP_IE_SDBE_BIT)

// (RW) DMA setup FIS interrupt enable
#define AHCI_HP_IE_DSE            (AHCI_HP_IE_DSE_MASK << AHCI_HP_IE_DSE_BIT)

// (RW) PIO setup FIS interrupt enable
#define AHCI_HP_IE_PSE            (AHCI_HP_IE_PSE_MASK << AHCI_HP_IE_PSE_BIT)

// (RW) D2H FIS interrupt enable
#define AHCI_HP_IE_DHRE           (AHCI_HP_IE_DHRE_MASK << AHCI_HP_IE_DHRE_BIT)

#define AHCI_HP_IE_CPDE_n(n)      ((n) << AHCI_HP_IE_CPDE_BIT)
#define AHCI_HP_IE_TFEE_n(n)      ((n) << AHCI_HP_IE_TFEE_BIT)
#define AHCI_HP_IE_HBFE_n(n)      ((n) << AHCI_HP_IE_HBFE_BIT)
#define AHCI_HP_IE_HBDE_n(n)      ((n) << AHCI_HP_IE_HBDE_BIT)
#define AHCI_HP_IE_IFE_n(n)       ((n) << AHCI_HP_IE_IFE_BIT)
#define AHCI_HP_IE_INFE_n(n)      ((n) << AHCI_HP_IE_INFE_BIT)
#define AHCI_HP_IE_OFE_n(n)       ((n) << AHCI_HP_IE_OFE_BIT)
#define AHCI_HP_IE_IPME_n(n)      ((n) << AHCI_HP_IE_IPME_BIT)
#define AHCI_HP_IE_PRCE_n(n)      ((n) << AHCI_HP_IE_PRCE_BIT)
#define AHCI_HP_IE_DMPE_n(n)      ((n) << AHCI_HP_IE_DMPE_BIT)
#define AHCI_HP_IE_PCE_n(n)       ((n) << AHCI_HP_IE_PCE_BIT)
#define AHCI_HP_IE_DPE_n(n)       ((n) << AHCI_HP_IE_DPE_BIT)
#define AHCI_HP_IE_UFE_n(n)       ((n) << AHCI_HP_IE_UFE_BIT)
#define AHCI_HP_IE_SDBE_n(n)      ((n) << AHCI_HP_IE_SDBE_BIT)
#define AHCI_HP_IE_DSE_n(n)       ((n) << AHCI_HP_IE_DSE_BIT)
#define AHCI_HP_IE_PSE_n(n)       ((n) << AHCI_HP_IE_PSE_BIT)
#define AHCI_HP_IE_DHRE_n(n)      ((n) << AHCI_HP_IE_DHRE_BIT)

#define AHCI_HP_IE_CPDE_GET(n) \
    (((n) >> AHCI_HP_IE_CPDE_BIT) & AHCI_HP_IE_CPDE_MASK)
#define AHCI_HP_IE_TFEE_GET(n) \
    (((n) >> AHCI_HP_IE_TFEE_BIT) & AHCI_HP_IE_TFEE_MASK)
#define AHCI_HP_IE_HBFE_GET(n) \
    (((n) >> AHCI_HP_IE_HBFE_BIT) & AHCI_HP_IE_HBFE_MASK)
#define AHCI_HP_IE_HBDE_GET(n) \
    (((n) >> AHCI_HP_IE_HBDE_BIT) & AHCI_HP_IE_HBDE_MASK)
#define AHCI_HP_IE_IFE_GET(n) \
    (((n) >> AHCI_HP_IE_IFE_BIT) & AHCI_HP_IE_IFE_MASK)
#define AHCI_HP_IE_INFE_GET(n) \
    (((n) >> AHCI_HP_IE_INFE_BIT) & AHCI_HP_IE_INFE_MASK)
#define AHCI_HP_IE_OFE_GET(n) \
    (((n) >> AHCI_HP_IE_OFE_BIT) & AHCI_HP_IE_OFE_MASK)
#define AHCI_HP_IE_IPME_GET(n) \
    (((n) >> AHCI_HP_IE_IPME_BIT) & AHCI_HP_IE_IPME_MASK)
#define AHCI_HP_IE_PRCE_GET(n) \
    (((n) >> AHCI_HP_IE_PRCE_BIT) & AHCI_HP_IE_PRCE_MASK)
#define AHCI_HP_IE_DMPE_GET(n) \
    (((n) >> AHCI_HP_IE_DMPE_BIT) & AHCI_HP_IE_DMPE_MASK)
#define AHCI_HP_IE_PCE_GET(n) \
    (((n) >> AHCI_HP_IE_PCE_BIT) & AHCI_HP_IE_PCE_MASK)
#define AHCI_HP_IE_DPE_GET(n) \
    (((n) >> AHCI_HP_IE_DPE_BIT) & AHCI_HP_IE_DPE_MASK)
#define AHCI_HP_IE_UFE_GET(n) \
    (((n) >> AHCI_HP_IE_UFE_BIT) & AHCI_HP_IE_UFE_MASK)
#define AHCI_HP_IE_SDBE_GET(n) \
    (((n) >> AHCI_HP_IE_SDBE_BIT) & AHCI_HP_IE_SDBE_MASK)
#define AHCI_HP_IE_DSE_GET(n) \
    (((n) >> AHCI_HP_IE_DSE_BIT) & AHCI_HP_IE_DSE_MASK)
#define AHCI_HP_IE_PSE_GET(n) \
    (((n) >> AHCI_HP_IE_PSE_BIT) & AHCI_HP_IE_PSE_MASK)
#define AHCI_HP_IE_DHRE_GET(n) \
    (((n) >> AHCI_HP_IE_DHRE_BIT) & AHCI_HP_IE_DHRE_MASK)

#define AHCI_HP_IE_CPDE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_CPDE) | AHCI_HP_IE_CPDE_n((n)))
#define AHCI_HP_IE_TFEE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_TFEE) | AHCI_HP_IE_TFEE_n((n)))
#define AHCI_HP_IE_HBFE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_HBFE) | AHCI_HP_IE_HBFE_n((n)))
#define AHCI_HP_IE_HBDE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_HBDE) | AHCI_HP_IE_HBDE_n((n)))
#define AHCI_HP_IE_IFE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_IFE) | AHCI_HP_IE_IFE_n((n)))
#define AHCI_HP_IE_INFE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_INFE) | AHCI_HP_IE_INFE_n((n)))
#define AHCI_HP_IE_OFE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_OFE) | AHCI_HP_IE_OFE_n((n)))
#define AHCI_HP_IE_IPME_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_IPME) | AHCI_HP_IE_IPME_n((n)))
#define AHCI_HP_IE_PRCE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_PRCE) | AHCI_HP_IE_PRCE_n((n)))
#define AHCI_HP_IE_DMPE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_DMPE) | AHCI_HP_IE_DMPE_n((n)))
#define AHCI_HP_IE_PCE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_PCE) | AHCI_HP_IE_PCE_n((n)))
#define AHCI_HP_IE_DPE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_DPE) | AHCI_HP_IE_DPE_n((n)))
#define AHCI_HP_IE_UFE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_UFE) | AHCI_HP_IE_UFE_n((n)))
#define AHCI_HP_IE_SDBE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_SDBE) | AHCI_HP_IE_SDBE_n((n)))
#define AHCI_HP_IE_DSE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_DSE) | AHCI_HP_IE_DSE_n((n)))
#define AHCI_HP_IE_PSE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_PSE) | AHCI_HP_IE_PSE_n((n)))
#define AHCI_HP_IE_DHRE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_IE_DHRE) | AHCI_HP_IE_DHRE_n((n)))

//
// AHCI_HP_CMD: 3.3.7 Port command and status

#define AHCI_HP_CMD_ICC_BIT         28
#define AHCI_HP_CMD_ASP_BIT         27
#define AHCI_HP_CMD_ALPE_BIT        26
#define AHCI_HP_CMD_DLAE_BIT        25
#define AHCI_HP_CMD_ATAPI_BIT       24
#define AHCI_HP_CMD_APSTE_BIT       23
#define AHCI_HP_CMD_FBSCP_BIT       22
#define AHCI_HP_CMD_ESP_BIT         21
#define AHCI_HP_CMD_CPD_BIT         20
#define AHCI_HP_CMD_MPSP_BIT        19
#define AHCI_HP_CMD_HPCP_BIT        18
#define AHCI_HP_CMD_PMA_BIT         17
#define AHCI_HP_CMD_CPS_BIT         16
#define AHCI_HP_CMD_CR_BIT          15
#define AHCI_HP_CMD_FR_BIT          14
#define AHCI_HP_CMD_MPSS_BIT        13
#define AHCI_HP_CMD_CCS_BIT         8
#define AHCI_HP_CMD_FRE_BIT         4
#define AHCI_HP_CMD_CLO_BIT         3
#define AHCI_HP_CMD_POD_BIT         2
#define AHCI_HP_CMD_SUD_BIT         1
#define AHCI_HP_CMD_ST_BIT          0

#define AHCI_HP_CMD_ICC_BITS        4
#define AHCI_HP_CMD_ASP_BITS        1
#define AHCI_HP_CMD_ALPE_BITS       1
#define AHCI_HP_CMD_DLAE_BITS       1
#define AHCI_HP_CMD_ATAPI_BITS      1
#define AHCI_HP_CMD_APSTE_BITS      1
#define AHCI_HP_CMD_FBSCP_BITS      1
#define AHCI_HP_CMD_ESP_BITS        1
#define AHCI_HP_CMD_CPD_BITS        1
#define AHCI_HP_CMD_MPSP_BITS       1
#define AHCI_HP_CMD_HPCP_BITS       1
#define AHCI_HP_CMD_PMA_BITS        1
#define AHCI_HP_CMD_CPS_BITS        1
#define AHCI_HP_CMD_CR_BITS         1
#define AHCI_HP_CMD_FR_BITS         1
#define AHCI_HP_CMD_MPSS_BITS       1
#define AHCI_HP_CMD_CCS_BITS        5
#define AHCI_HP_CMD_FRE_BITS        1
#define AHCI_HP_CMD_CLO_BITS        1
#define AHCI_HP_CMD_POD_BITS        1
#define AHCI_HP_CMD_SUD_BITS        1
#define AHCI_HP_CMD_ST_BITS         1
#define AHCI_HP_CMD_ICC_MASK        ((1U << AHCI_HP_CMD_ICC_BITS)-1)
#define AHCI_HP_CMD_ASP_MASK        ((1U << AHCI_HP_CMD_ASP_BITS)-1)
#define AHCI_HP_CMD_ALPE_MASK       ((1U << AHCI_HP_CMD_ALPE_BITS)-1)
#define AHCI_HP_CMD_DLAE_MASK       ((1U << AHCI_HP_CMD_DLAE_BITS)-1)
#define AHCI_HP_CMD_ATAPI_MASK      ((1U << AHCI_HP_CMD_ATAPI_BITS)-1)
#define AHCI_HP_CMD_APSTE_MASK      ((1U << AHCI_HP_CMD_APSTE_BITS)-1)
#define AHCI_HP_CMD_FBSCP_MASK      ((1U << AHCI_HP_CMD_FBSCP_BITS)-1)
#define AHCI_HP_CMD_ESP_MASK        ((1U << AHCI_HP_CMD_ESP_BITS)-1)
#define AHCI_HP_CMD_CPD_MASK        ((1U << AHCI_HP_CMD_CPD_BITS)-1)
#define AHCI_HP_CMD_MPSP_MASK       ((1U << AHCI_HP_CMD_MPSP_BITS)-1)
#define AHCI_HP_CMD_HPCP_MASK       ((1U << AHCI_HP_CMD_HPCP_BITS)-1)
#define AHCI_HP_CMD_PMA_MASK        ((1U << AHCI_HP_CMD_PMA_BITS)-1)
#define AHCI_HP_CMD_CPS_MASK        ((1U << AHCI_HP_CMD_CPS_BITS)-1)
#define AHCI_HP_CMD_CR_MASK         ((1U << AHCI_HP_CMD_CR_BITS)-1)
#define AHCI_HP_CMD_FR_MASK         ((1U << AHCI_HP_CMD_FR_BITS)-1)
#define AHCI_HP_CMD_MPSS_MASK       ((1U << AHCI_HP_CMD_MPSS_BITS)-1)
#define AHCI_HP_CMD_CCS_MASK        ((1U << AHCI_HP_CMD_CCS_BITS)-1)
#define AHCI_HP_CMD_FRE_MASK        ((1U << AHCI_HP_CMD_FRE_BITS)-1)
#define AHCI_HP_CMD_CLO_MASK        ((1U << AHCI_HP_CMD_CLO_BITS)-1)
#define AHCI_HP_CMD_POD_MASK        ((1U << AHCI_HP_CMD_POD_BITS)-1)
#define AHCI_HP_CMD_SUD_MASK        ((1U << AHCI_HP_CMD_SUD_BITS)-1)
#define AHCI_HP_CMD_ST_MASK         ((1U << AHCI_HP_CMD_ST_BITS)-1)

// Interface communication control
#define AHCI_HP_CMD_ICC \
    (AHCI_HP_CMD_ICC_MASK << AHCI_HP_CMD_ICC_BIT)

// Aggressive slumber/partial
#define AHCI_HP_CMD_ASP \
    (AHCI_HP_CMD_ASP_MASK << AHCI_HP_CMD_ASP_BIT)

// Aggressive link power management enabled
#define AHCI_HP_CMD_ALPE \
    (AHCI_HP_CMD_ALPE_MASK << AHCI_HP_CMD_ALPE_BIT)

// Drive LED on ATAPI enable
#define AHCI_HP_CMD_DLAE \
    (AHCI_HP_CMD_DLAE_MASK << AHCI_HP_CMD_DLAE_BIT)

// Device is ATAPI
#define AHCI_HP_CMD_ATAPI \
    (AHCI_HP_CMD_ATAPI_MASK << AHCI_HP_CMD_ATAPI_BIT)

// Automatic partial to slumber transitions enabled
#define AHCI_HP_CMD_APSTE \
    (AHCI_HP_CMD_APSTE_MASK << AHCI_HP_CMD_APSTE_BIT)

// FIS based switching capable port
#define AHCI_HP_CMD_FBSCP \
    (AHCI_HP_CMD_FBSCP_MASK << AHCI_HP_CMD_FBSCP_BIT)

// External SATA port
#define AHCI_HP_CMD_ESP \
    (AHCI_HP_CMD_ESP_MASK << AHCI_HP_CMD_ESP_BIT)

// Cold presence detection
#define AHCI_HP_CMD_CPD \
    (AHCI_HP_CMD_CPD_MASK << AHCI_HP_CMD_CPD_BIT)

// Mechanical presence switch attached to port
#define AHCI_HP_CMD_MPSP \
    (AHCI_HP_CMD_MPSP_MASK << AHCI_HP_CMD_MPSP_BIT)

// Hot plug capable port
#define AHCI_HP_CMD_HPCP \
    (AHCI_HP_CMD_HPCP_MASK << AHCI_HP_CMD_HPCP_BIT)

// Port multiplier attached
#define AHCI_HP_CMD_PMA \
    (AHCI_HP_CMD_PMA_MASK << AHCI_HP_CMD_PMA_BIT)

// Cold presence state
#define AHCI_HP_CMD_CPS \
    (AHCI_HP_CMD_CPS_MASK << AHCI_HP_CMD_CPS_BIT)

// Command list running
#define AHCI_HP_CMD_CR              (AHCI_HP_CMD_CR_MASK << AHCI_HP_CMD_CR_BIT)

// FIS receive running
#define AHCI_HP_CMD_FR              (AHCI_HP_CMD_FR_MASK << AHCI_HP_CMD_FR_BIT)

// Mechanical presence switch state
#define AHCI_HP_CMD_MPSS \
    (AHCI_HP_CMD_MPSS_MASK << AHCI_HP_CMD_MPSS_BIT)

// Current command slot
#define AHCI_HP_CMD_CCS \
    (AHCI_HP_CMD_CCS_MASK << AHCI_HP_CMD_CCS_BIT)

// FIS receive enable
#define AHCI_HP_CMD_FRE \
    (AHCI_HP_CMD_FRE_MASK << AHCI_HP_CMD_FRE_BIT)

// Command list override
#define AHCI_HP_CMD_CLO \
    (AHCI_HP_CMD_CLO_MASK << AHCI_HP_CMD_CLO_BIT)

// Power on device
#define AHCI_HP_CMD_POD \
    (AHCI_HP_CMD_POD_MASK << AHCI_HP_CMD_POD_BIT)

// Spin up device
#define AHCI_HP_CMD_SUD \
    (AHCI_HP_CMD_SUD_MASK << AHCI_HP_CMD_SUD_BIT)

// Start
#define AHCI_HP_CMD_ST              (AHCI_HP_CMD_ST_MASK << AHCI_HP_CMD_ST_BIT)

#define AHCI_HP_CMD_ICC_n(n)        ((n) << AHCI_HP_CMD_ICC_BIT)
#define AHCI_HP_CMD_ASP_n(n)        ((n) << AHCI_HP_CMD_ASP_BIT)
#define AHCI_HP_CMD_ALPE_n(n)       ((n) << AHCI_HP_CMD_ALPE_BIT)
#define AHCI_HP_CMD_DLAE_n(n)       ((n) << AHCI_HP_CMD_DLAE_BIT)
#define AHCI_HP_CMD_ATAPI_n(n)      ((n) << AHCI_HP_CMD_ATAPI_BIT)
#define AHCI_HP_CMD_APSTE_n(n)      ((n) << AHCI_HP_CMD_APSTE_BIT)
#define AHCI_HP_CMD_FBSCP_n(n)      ((n) << AHCI_HP_CMD_FBSCP_BIT)
#define AHCI_HP_CMD_ESP_n(n)        ((n) << AHCI_HP_CMD_ESP_BIT)
#define AHCI_HP_CMD_CPD_n(n)        ((n) << AHCI_HP_CMD_CPD_BIT)
#define AHCI_HP_CMD_MPSP_n(n)       ((n) << AHCI_HP_CMD_MPSP_BIT)
#define AHCI_HP_CMD_HPCP_n(n)       ((n) << AHCI_HP_CMD_HPCP_BIT)
#define AHCI_HP_CMD_PMA_n(n)        ((n) << AHCI_HP_CMD_PMA_BIT)
#define AHCI_HP_CMD_CPS_n(n)        ((n) << AHCI_HP_CMD_CPS_BIT)
#define AHCI_HP_CMD_CR_n(n)         ((n) << AHCI_HP_CMD_CR_BIT)
#define AHCI_HP_CMD_FR_n(n)         ((n) << AHCI_HP_CMD_FR_BIT)
#define AHCI_HP_CMD_MPSS_n(n)       ((n) << AHCI_HP_CMD_MPSS_BIT)
#define AHCI_HP_CMD_CCS_n(n)        ((n) << AHCI_HP_CMD_CCS_BIT)
#define AHCI_HP_CMD_FRE_n(n)        ((n) << AHCI_HP_CMD_FRE_BIT)
#define AHCI_HP_CMD_CLO_n(n)        ((n) << AHCI_HP_CMD_CLO_BIT)
#define AHCI_HP_CMD_POD_n(n)        ((n) << AHCI_HP_CMD_POD_BIT)
#define AHCI_HP_CMD_SUD_n(n)        ((n) << AHCI_HP_CMD_SUD_BIT)
#define AHCI_HP_CMD_ST_n(n)         ((n) << AHCI_HP_CMD_ST_BIT)

#define AHCI_HP_CMD_ICC_GET(n) \
    (((n) >> AHCI_HP_CMD_ICC_BIT) & AHCI_HP_CMD_ICC_MASK)
#define AHCI_HP_CMD_ASP_GET(n) \
    (((n) >> AHCI_HP_CMD_ASP_BIT) & AHCI_HP_CMD_ASP_MASK)
#define AHCI_HP_CMD_ALPE_GET(n) \
    (((n) >> AHCI_HP_CMD_ALPE_BIT) & AHCI_HP_CMD_ALPE_MASK)
#define AHCI_HP_CMD_DLAE_GET(n) \
    (((n) >> AHCI_HP_CMD_DLAE_BIT) & AHCI_HP_CMD_DLAE_MASK)
#define AHCI_HP_CMD_ATAPI_GET(n) \
    (((n) >> AHCI_HP_CMD_ATAPI_BIT) & AHCI_HP_CMD_ATAPI_MASK)
#define AHCI_HP_CMD_APSTE_GET(n) \
    (((n) >> AHCI_HP_CMD_APSTE_BIT) & AHCI_HP_CMD_APSTE_MASK)
#define AHCI_HP_CMD_FBSCP_GET(n) \
    (((n) >> AHCI_HP_CMD_FBSCP_BIT) & AHCI_HP_CMD_FBSCP_MASK)
#define AHCI_HP_CMD_ESP_GET(n) \
    (((n) >> AHCI_HP_CMD_ESP_BIT) & AHCI_HP_CMD_ESP_MASK)
#define AHCI_HP_CMD_CPD_GET(n) \
    (((n) >> AHCI_HP_CMD_CPD_BIT) & AHCI_HP_CMD_CPD_MASK)
#define AHCI_HP_CMD_MPSP_GET(n) \
    (((n) >> AHCI_HP_CMD_MPSP_BIT) & AHCI_HP_CMD_MPSP_MASK)
#define AHCI_HP_CMD_HPCP_GET(n) \
    (((n) >> AHCI_HP_CMD_HPCP_BIT) & AHCI_HP_CMD_HPCP_MASK)
#define AHCI_HP_CMD_PMA_GET(n) \
    (((n) >> AHCI_HP_CMD_PMA_BIT) & AHCI_HP_CMD_PMA_MASK)
#define AHCI_HP_CMD_CPS_GET(n) \
    (((n) >> AHCI_HP_CMD_CPS_BIT) & AHCI_HP_CMD_CPS_MASK)
#define AHCI_HP_CMD_CR_GET(n) \
    (((n) >> AHCI_HP_CMD_CR_BIT) & AHCI_HP_CMD_CR_MASK)
#define AHCI_HP_CMD_FR_GET(n) \
    (((n) >> AHCI_HP_CMD_FR_BIT) & AHCI_HP_CMD_FR_MASK)
#define AHCI_HP_CMD_MPSS_GET(n) \
    (((n) >> AHCI_HP_CMD_MPSS_BIT) & AHCI_HP_CMD_MPSS_MASK)
#define AHCI_HP_CMD_CCS_GET(n) \
    (((n) >> AHCI_HP_CMD_CCS_BIT) & AHCI_HP_CMD_CCS_MASK)
#define AHCI_HP_CMD_FRE_GET(n) \
    (((n) >> AHCI_HP_CMD_FRE_BIT) & AHCI_HP_CMD_FRE_MASK)
#define AHCI_HP_CMD_CLO_GET(n) \
    (((n) >> AHCI_HP_CMD_CLO_BIT) & AHCI_HP_CMD_CLO_MASK)
#define AHCI_HP_CMD_POD_GET(n) \
    (((n) >> AHCI_HP_CMD_POD_BIT) & AHCI_HP_CMD_POD_MASK)
#define AHCI_HP_CMD_SUD_GET(n) \
    (((n) >> AHCI_HP_CMD_SUD_BIT) & AHCI_HP_CMD_SUD_MASK)
#define AHCI_HP_CMD_ST_GET(n) \
    (((n) >> AHCI_HP_CMD_ST_BIT) & AHCI_HP_CMD_ST_MASK)

#define AHCI_HP_CMD_ICC_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ICC) | AHCI_HP_CMD_ICC_n((n)))
#define AHCI_HP_CMD_ASP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ASP) | AHCI_HP_CMD_ASP_n((n)))
#define AHCI_HP_CMD_ALPE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ALPE) | AHCI_HP_CMD_ALPE_n((n)))
#define AHCI_HP_CMD_DLAE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_DLAE) | AHCI_HP_CMD_DLAE_n((n)))
#define AHCI_HP_CMD_ATAPI_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ATAPI) | AHCI_HP_CMD_ATAPI_n((n)))
#define AHCI_HP_CMD_APSTE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_APSTE) | AHCI_HP_CMD_APSTE_n((n)))
#define AHCI_HP_CMD_FBSCP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_FBSCP) | AHCI_HP_CMD_FBSCP_n((n)))
#define AHCI_HP_CMD_ESP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ESP) | AHCI_HP_CMD_ESP_n((n)))
#define AHCI_HP_CMD_CPD_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_CPD) | AHCI_HP_CMD_CPD_n((n)))
#define AHCI_HP_CMD_MPSP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_MPSP) | AHCI_HP_CMD_MPSP_n((n)))
#define AHCI_HP_CMD_HPCP_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_HPCP) | AHCI_HP_CMD_HPCP_n((n)))
#define AHCI_HP_CMD_PMA_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_PMA) | AHCI_HP_CMD_PMA_n((n)))
#define AHCI_HP_CMD_CPS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_CPS) | AHCI_HP_CMD_CPS_n((n)))
#define AHCI_HP_CMD_CR_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_CR) | AHCI_HP_CMD_CR_n((n)))
#define AHCI_HP_CMD_FR_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_FR) | AHCI_HP_CMD_FR_n((n)))
#define AHCI_HP_CMD_MPSS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_MPSS) | AHCI_HP_CMD_MPSS_n((n)))
#define AHCI_HP_CMD_CCS_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_CCS) | AHCI_HP_CMD_CCS_n((n)))
#define AHCI_HP_CMD_FRE_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_FRE) | AHCI_HP_CMD_FRE_n((n)))
#define AHCI_HP_CMD_CLO_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_CLO) | AHCI_HP_CMD_CLO_n((n)))
#define AHCI_HP_CMD_POD_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_POD) | AHCI_HP_CMD_POD_n((n)))
#define AHCI_HP_CMD_SUD_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_SUD) | AHCI_HP_CMD_SUD_n((n)))
#define AHCI_HP_CMD_ST_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_CMD_ST) | AHCI_HP_CMD_ST_n((n)))

//
// AHCI_HP_SIG: 3.3.9 Port signature

#define AHCI_HP_SIG_HIGH_BIT           24
#define AHCI_HP_SIG_MID_BIT            16
#define AHCI_HP_SIG_LOW_BIT            8
#define AHCI_HP_SIG_SECCOUNT_BIT       0

#define AHCI_HP_SIG_HIGH_BITS          8
#define AHCI_HP_SIG_MID_BITS           8
#define AHCI_HP_SIG_LOW_BITS           8
#define AHCI_HP_SIG_SECCOUNT_BITS      8
#define AHCI_HP_SIG_HIGH_MASK          ((1U << AHCI_HP_SIG_HIGH_BITS)-1)
#define AHCI_HP_SIG_MID_MASK           ((1U << AHCI_HP_SIG_MID_BITS)-1)
#define AHCI_HP_SIG_LOW_MASK           ((1U << AHCI_HP_SIG_LOW_BITS)-1)
#define AHCI_HP_SIG_SECCOUNT_MASK      ((1U << AHCI_HP_SIG_SECCOUNT_BITS)-1)

// LBA high
#define AHCI_HP_SIG_HIGH \
    (AHCI_HP_SIG_HIGH_MASK << AHCI_HP_SIG_HIGH_BIT)

// LBA mid
#define AHCI_HP_SIG_MID \
    (AHCI_HP_SIG_MID_MASK << AHCI_HP_SIG_MID_BIT)

// LBA low
#define AHCI_HP_SIG_LOW \
    (AHCI_HP_SIG_LOW_MASK << AHCI_HP_SIG_LOW_BIT)
#define AHCI_HP_SIG_SECCOUNT \
    (AHCI_HP_SIG_SECCOUNT_MASK << AHCI_HP_SIG_SECCOUNT_BIT)

#define AHCI_HP_SIG_HIGH_n(n)          ((n) << AHCI_HP_SIG_HIGH_BIT)
#define AHCI_HP_SIG_MID_n(n)           ((n) << AHCI_HP_SIG_MID_BIT)
#define AHCI_HP_SIG_LOW_n(n)           ((n) << AHCI_HP_SIG_LOW_BIT)
#define AHCI_HP_SIG_SECCOUNT_n(n)      ((n) << AHCI_HP_SIG_SECCOUNT_BIT)

#define AHCI_HP_SIG_HIGH_GET(n) \
    (((n) >> AHCI_HP_SIG_HIGH_BIT) & AHCI_HP_SIG_HIGH_MASK)
#define AHCI_HP_SIG_MID_GET(n) \
    (((n) >> AHCI_HP_SIG_MID_BIT) & AHCI_HP_SIG_MID_MASK)
#define AHCI_HP_SIG_LOW_GET(n) \
    (((n) >> AHCI_HP_SIG_LOW_BIT) & AHCI_HP_SIG_LOW_MASK)
#define AHCI_HP_SIG_SECCOUNT_GET(n) \
    (((n) >> AHCI_HP_SIG_SECCOUNT_BIT) & AHCI_HP_SIG_SECCOUNT_MASK)

#define AHCI_HP_SIG_HIGH_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SIG_HIGH) | AHCI_HP_SIG_HIGH_n((n)))
#define AHCI_HP_SIG_MID_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SIG_MID) | AHCI_HP_SIG_MID_n((n)))
#define AHCI_HP_SIG_LOW_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SIG_LOW) | AHCI_HP_SIG_LOW_n((n)))
#define AHCI_HP_SIG_SECCOUNT_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SIG_SECCOUNT) | AHCI_HP_SIG_SECCOUNT_n((n)))

//
// AHCI_HP_SS: 3.3.10 Port SATA status

#define AHCI_HP_SS_IPM_BIT       8
#define AHCI_HP_SS_SPD_BIT       4
#define AHCI_HP_SS_DET_BIT       0

#define AHCI_HP_SS_IPM_BITS      4
#define AHCI_HP_SS_SPD_BITS      4
#define AHCI_HP_SS_DET_BITS      4
#define AHCI_HP_SS_IPM_MASK      ((1U << AHCI_HP_SS_IPM_BITS)-1)
#define AHCI_HP_SS_SPD_MASK      ((1U << AHCI_HP_SS_SPD_BITS)-1)
#define AHCI_HP_SS_DET_MASK      ((1U << AHCI_HP_SS_DET_BITS)-1)

// Interface power management
#define AHCI_HP_SS_IPM           (AHCI_HP_SS_IPM_MASK << AHCI_HP_SS_IPM_BIT)

// Interface speed
#define AHCI_HP_SS_SPD           (AHCI_HP_SS_SPD_MASK << AHCI_HP_SS_SPD_BIT)

// Device detection
#define AHCI_HP_SS_DET           (AHCI_HP_SS_DET_MASK << AHCI_HP_SS_DET_BIT)

#define AHCI_HP_SS_IPM_n(n)      ((n) << AHCI_HP_SS_IPM_BIT)
#define AHCI_HP_SS_SPD_n(n)      ((n) << AHCI_HP_SS_SPD_BIT)
#define AHCI_HP_SS_DET_n(n)      ((n) << AHCI_HP_SS_DET_BIT)

#define AHCI_HP_SS_IPM_GET(n) \
    (((n) >> AHCI_HP_SS_IPM_BIT) & AHCI_HP_SS_IPM_MASK)
#define AHCI_HP_SS_SPD_GET(n) \
    (((n) >> AHCI_HP_SS_SPD_BIT) & AHCI_HP_SS_SPD_MASK)
#define AHCI_HP_SS_DET_GET(n) \
    (((n) >> AHCI_HP_SS_DET_BIT) & AHCI_HP_SS_DET_MASK)

#define AHCI_HP_SS_IPM_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SS_IPM) | AHCI_HP_SS_IPM_n((n)))
#define AHCI_HP_SS_SPD_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SS_SPD) | AHCI_HP_SS_SPD_n((n)))
#define AHCI_HP_SS_DET_SET(r,n) \
    ((r) = ((r) & ~AHCI_HP_SS_DET) | AHCI_HP_SS_DET_n((n)))

// AHCI_HP_SS_DET_NODEV
#define AHCI_HP_SS_DET_NODEV 0






// AHCI_HP_SS_DET_NOPHY
#define AHCI_HP_SS_DET_NOPHY 1






// AHCI_HP_SS_DET_ONLINE
#define AHCI_HP_SS_DET_ONLINE 3






// AHCI_HP_SS_DET_OFFLINE
#define AHCI_HP_SS_DET_OFFLINE 4






// AHCI_HP_SS_SPD_NODEV
#define AHCI_HP_SS_SPD_NODEV 0






// AHCI_HP_SS_SPD_GEN1
#define AHCI_HP_SS_SPD_GEN1 1






// AHCI_HP_SS_SPD_GEN2
#define AHCI_HP_SS_SPD_GEN2 2






// AHCI_HP_SS_SPD_GEN3
#define AHCI_HP_SS_SPD_GEN3 3






// AHCI_HP_SS_IPM_NODEV
#define AHCI_HP_SS_IPM_NODEV 0






// AHCI_HP_SS_IPM_ACTIVE
#define AHCI_HP_SS_IPM_ACTIVE 1






// AHCI_HP_SS_IPM_PARTIAL
#define AHCI_HP_SS_IPM_PARTIAL 2






// AHCI_HP_SS_IPM_SLUMBER
#define AHCI_HP_SS_IPM_SLUMBER 6






// AHCI_HP_SS_IPM_DEVSLEEP
#define AHCI_HP_SS_IPM_DEVSLEEP 8






