#pragma once

// Exception handlers
extern void isr_entry_0(void);
extern void isr_entry_1(void);
extern void isr_entry_2(void);
extern void isr_entry_3(void);
extern void isr_entry_4(void);
extern void isr_entry_5(void);
extern void isr_entry_6(void);
extern void isr_entry_7(void);
extern void isr_entry_8(void);
extern void isr_entry_9(void);
extern void isr_entry_10(void);
extern void isr_entry_11(void);
extern void isr_entry_12(void);
extern void isr_entry_13(void);
extern void isr_entry_14(void);
extern void isr_entry_15(void);
extern void isr_entry_16(void);
extern void isr_entry_17(void);
extern void isr_entry_18(void);
extern void isr_entry_19(void);
extern void isr_entry_20(void);
extern void isr_entry_21(void);
extern void isr_entry_22(void);
extern void isr_entry_23(void);
extern void isr_entry_24(void);
extern void isr_entry_25(void);
extern void isr_entry_26(void);
extern void isr_entry_27(void);
extern void isr_entry_28(void);
extern void isr_entry_29(void);
extern void isr_entry_30(void);
extern void isr_entry_31(void);

// PIC IRQs
extern void isr_entry_32(void);
extern void isr_entry_33(void);
extern void isr_entry_34(void);
extern void isr_entry_35(void);
extern void isr_entry_36(void);
extern void isr_entry_37(void);
extern void isr_entry_38(void);
extern void isr_entry_39(void);
extern void isr_entry_40(void);
extern void isr_entry_41(void);
extern void isr_entry_42(void);
extern void isr_entry_43(void);
extern void isr_entry_44(void);
extern void isr_entry_45(void);
extern void isr_entry_46(void);
extern void isr_entry_47(void);

// APIC IRQs
extern void isr_entry_48(void);
extern void isr_entry_49(void);
extern void isr_entry_50(void);
extern void isr_entry_51(void);
extern void isr_entry_52(void);
extern void isr_entry_53(void);
extern void isr_entry_54(void);
extern void isr_entry_55(void);
extern void isr_entry_56(void);
extern void isr_entry_57(void);
extern void isr_entry_58(void);
extern void isr_entry_59(void);
extern void isr_entry_60(void);
extern void isr_entry_61(void);
extern void isr_entry_62(void);
extern void isr_entry_63(void);
extern void isr_entry_64(void);
extern void isr_entry_65(void);
extern void isr_entry_66(void);
extern void isr_entry_67(void);
extern void isr_entry_68(void);
extern void isr_entry_69(void);
extern void isr_entry_70(void);
extern void isr_entry_71(void);

// Forced context switch
extern void isr_entry_72(void);
