#include "syscall_dispatch.h"
#include "types.h"
#include "asm_constants.h"
#include "errno.h"
#include "assert.h"

#include "syscall/sys_fd.h"
#include "syscall/sys_mem.h"
#include "syscall/sys_time.h"
#include "syscall/sys_process.h"
#include "syscall/sys_module.h"
#include "syscall/sys_sys.h"
#include "syscall/sys_render.h"

long sys_unimplemented()
{
    return -int(errno_t::ENOSYS);
}

uint8_t syscall_zmasks[SYSCALL_COUNT] = {};

syscall_handler_t *syscall_handlers[SYSCALL_COUNT] = {
    // 0x00
    (syscall_handler_t*)(void*)sys_read,
    (syscall_handler_t*)(void*)sys_write,
    (syscall_handler_t*)(void*)sys_open,
    (syscall_handler_t*)(void*)sys_close,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_newstat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_newfstat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_newlstat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_poll,
    (syscall_handler_t*)(void*)sys_lseek,
    (syscall_handler_t*)(void*)sys_mmap,
    (syscall_handler_t*)(void*)sys_mprotect,
    (syscall_handler_t*)(void*)sys_munmap,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_brk,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigaction,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigprocmask,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_stub_rt_sigreturn,
    // 0x10
    (syscall_handler_t*)(void*)sys_ioctl,
    (syscall_handler_t*)(void*)sys_pread64,
    (syscall_handler_t*)(void*)sys_pwrite64,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_readv,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_writev,
    (syscall_handler_t*)(void*)sys_access,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pipe,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_select,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_yield,
    (syscall_handler_t*)(void*)sys_mremap,
    (syscall_handler_t*)(void*)sys_msync,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mincore,
    (syscall_handler_t*)(void*)sys_madvise,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_shmget,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_shmat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_shmctl,
    // 0x20
    (syscall_handler_t*)(void*)sys_dup,
    (syscall_handler_t*)(void*)sys_dup2,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pause,
    (syscall_handler_t*)(void*)sys_nanosleep,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getitimer,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_alarm,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setitimer,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sendfile,
    (syscall_handler_t*)(void*)sys_socket,
    (syscall_handler_t*)(void*)sys_connect,
    (syscall_handler_t*)(void*)sys_accept,
    (syscall_handler_t*)(void*)sys_sendto,
    (syscall_handler_t*)(void*)sys_recvfrom,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sendmsg,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_recvmsg,
    // 0x30
    (syscall_handler_t*)(void*)sys_shutdown,
    (syscall_handler_t*)(void*)sys_bind,
    (syscall_handler_t*)(void*)sys_listen,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getsockname,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpeername,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_socketpair,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setsockopt,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getsockopt,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clone,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fork,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_vfork,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_execve,
    (syscall_handler_t*)(void*)sys_exit,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_wait4,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_kill,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_uname,
    // 0x40
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_semget,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_semop,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_semctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_shmdt,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_msgget,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_msgsnd,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_msgrcv,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_msgctl,
    (syscall_handler_t*)(void*)sys_fcntl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_flock,
    (syscall_handler_t*)(void*)sys_fsync,
    (syscall_handler_t*)(void*)sys_fdatasync,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_truncate,
    (syscall_handler_t*)(void*)sys_ftruncate,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getdents,
    (syscall_handler_t*)(void*)sys_getcwd,
    // x50
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_chdir,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fchdir,
    (syscall_handler_t*)(void*)sys_rename,
    (syscall_handler_t*)(void*)sys_mkdir,
    (syscall_handler_t*)(void*)sys_rmdir,
    (syscall_handler_t*)(void*)sys_creat,
    (syscall_handler_t*)(void*)sys_link,
    (syscall_handler_t*)(void*)sys_unlink,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_symlink,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_readlink,
    (syscall_handler_t*)(void*)sys_chmod,
    (syscall_handler_t*)(void*)sys_fchmod,
    (syscall_handler_t*)(void*)sys_chown,
    (syscall_handler_t*)(void*)sys_fchown,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_lchown,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_umask,
    // 0x60
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_gettimeofday,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getrlimit,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getrusage,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sysinfo,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_times,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ptrace,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_syslog,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_geteuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getegid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setpgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getppid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpgrp,
    // 0x70
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setsid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setreuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setregid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getgroups,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setgroups,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setresuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getresuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setresgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getresgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setfsuid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setfsgid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getsid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_capget,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_capset,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigpending,
    // 0x80
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigtimedwait,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigqueueinfo,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_sigsuspend,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sigaltstack,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_utime,
    (syscall_handler_t*)(void*)sys_mknod,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_uselib,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_personality,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ustat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_statfs,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fstatfs,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sysfs,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpriority,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setpriority,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_setparam,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_getparam,
    // 0x90
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_setscheduler,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_getscheduler,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_get_priority_max,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_get_priority_min,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_rr_get_interval,
    (syscall_handler_t*)(void*)sys_mlock,
    (syscall_handler_t*)(void*)sys_munlock,
    (syscall_handler_t*)(void*)sys_mlockall,
    (syscall_handler_t*)(void*)sys_munlockall,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_vhangup,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_modify_ldt,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pivot_root,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys__sysctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_prctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_arch_prctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_adjtimex,
    // 0xA0
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setrlimit,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_chroot,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sync,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_acct,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_settimeofday,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mount,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_umount2,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_swapon,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_swapoff,
    (syscall_handler_t*)(void*)sys_reboot,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sethostname,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setdomainname,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_iopl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ioperm,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_create_module,
    (syscall_handler_t*)(void*)sys_init_module,
    // 0xB0
    (syscall_handler_t*)(void*)sys_delete_module,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_get_kernel_syms,
    (syscall_handler_t*)(void*)sys_query_module,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_quotactl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_nfsservctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getpmsg,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_putpmsg,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_afs_syscall,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_tuxcall,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_security,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_gettid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_readahead,
    (syscall_handler_t*)(void*)sys_setxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_lsetxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fsetxattr,
    (syscall_handler_t*)(void*)sys_getxattr,
    // 0xC0
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_lgetxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fgetxattr,
    (syscall_handler_t*)(void*)sys_listxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_llistxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_flistxattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_removexattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_lremovexattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fremovexattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_tkill,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_time,
    (syscall_handler_t*)(void*)sys_futex,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_setaffinity,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sched_getaffinity,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_set_thread_area,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_io_setup,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_io_destroy,
    // 0xD0
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_io_getevents,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_io_submit,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_io_cancel,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_get_thread_area,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_lookup_dcookie,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_create,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_ctl_old,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_wait_old,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_remap_file_pages,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getdents64,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_set_tid_address,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_restart_syscall,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_semtimedop,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fadvise64,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timer_create,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timer_settime,
    // 0xE0
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timer_gettime,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timer_getoverrun,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timer_delete,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clock_settime,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clock_gettime,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clock_getres,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clock_nanosleep,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_exit_group,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_wait,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_ctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_tgkill,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_utimes,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_vserver,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mbind,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_set_mempolicy,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_get_mempolicy,
    // 0xF0
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_open,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_unlink,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_timedsend,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_timedreceive,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_notify,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mq_getsetattr,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_kexec_load,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_waitid,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_add_key,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_request_key,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_keyctl,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ioprio_set,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ioprio_get,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_inotify_init,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_inotify_add_watch,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_inotify_rm_watch,
    // 0x100
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_migrate_pages,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_openat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mkdirat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_mknodat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fchownat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_futimesat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_newfstatat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_unlinkat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_renameat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_linkat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_symlinkat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_readlinkat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fchmodat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_faccessat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pselect6,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_ppoll,
    // 0x110
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_unshare,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_set_robust_list,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_get_robust_list,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_splice,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_tee,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sync_file_range,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_vmsplice,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_move_pages,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_utimensat,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_pwait,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_signalfd,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timerfd_create,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_eventfd,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fallocate,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timerfd_settime,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_timerfd_gettime,
    // 0x120
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_accept4,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_signalfd4,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_eventfd2,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_epoll_create1,
    (syscall_handler_t*)(void*)sys_dup3,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pipe2,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_inotify_init1,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_preadv,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_pwritev,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_rt_tgsigqueueinfo,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_perf_event_open,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_recvmmsg,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fanotify_init,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fanotify_mark,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_prlimit64,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_name_to_handle_at,
    // 0x130
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_open_by_handle_at,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_clock_adjtime,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_syncfs,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_sendmmsg,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_setns,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_getcpu,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_process_vm_readv,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_process_vm_writev,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_kcmp,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_finit_module,
    (syscall_handler_t*)(void*)sys_unimplemented,//sys_fexecve
    (syscall_handler_t*)(void*)sys_probe_pci_for,
    (syscall_handler_t*)(void*)sys_render_batch,
    (syscall_handler_t*)(void*)sys_posix_spawn,
    //(syscall_handler_t*)(void*)sys_,
    //(syscall_handler_t*)(void*)sys_,
};

C_ASSERT(countof(syscall_handlers) == SYSCALL_COUNT);
