# Compile libnet (processor independent code)

LIBNAME := net
CSRCS := \
	eth_q.cc \
	eth_frame.cc \
	arp_frame.cc \
	ipv4_frame.cc \
	tcp_frame.cc \
	udp_frame.cc \
	icmp_frame.cc \
	icmp.cc \
	ipv4.cc \
	udp.cc \
	tcp.cc \
	dhcp.cc

include $(BUILDROOT)/library.mk
