# Compile libnet (processor independent code)

LIBNAME := net
CSRCS := \
	eth_q.c \
	eth_frame.c \
	arp_frame.c \
	ipv4_frame.c \
	tcp_frame.c \
	udp_frame.c \
	icmp_frame.c \
	icmp.c \
	ipv4.c \
	udp.c \
	tcp.c \
	dhcp.c

include $(BUILDROOT)/library.mk
