#!/bin/bash

dir=.
if [[ -n $1 ]]; then
	dir=$1
fi

while read f; do
	echo ---- $f
	while read s; do
		if ! [[ -e ${f%/*}/$s ]]; then
			echo ${f%/*}/$s
		fi
	done < $f
done < <(find "$dir" -type f -name '*.files')
