# Compile libkernel (processor independent code)

LIBNAME := kernel
CSRCS := mm.c \
	tls.c \
	thread.c \
	printk.c \
	dev_text.c \
	dev_storage.c \
	conio.c \
	string.c \
	irq.c \
	time.c \
	mouse.c

include $(BUILDROOT)/library.mk
